### ISSUE TITLE
Unable to create thread pipe: Too many open files

### ISSUE THREAD

**Issue by andrew-dixon** [giakki/uncss#106]
When I add more than 10 URL's to the "files" list I get the following error:

> phantom stderr: QEventDispatcherUNIXPrivate(): Unable to create thread pipe: Too many open files
> 2014-11-08T23:48:23 [FATAL] QEventDispatcherUNIXPrivate(): Can not continue without a thread pipe
> Request() error evaluating open() call: Error: socket hang up
> Request() error evaluating open() call: Error: connect ECONNREFUSED
> Request() error evaluating open() call: Error: connect ECONNREFUSED
> Request() error evaluating open() call: Error: connect ECONNREFUSED

This is obviously a bit limiting when I want it to crawl an entire site and check all pages for CSS styles used. I have so far only used the example code, e.g.

``` javascript
var uncss = require('uncss');

var files   = [
      'http://www.domain.com',
      'http://www.domain.com/page1',
      'http://www.domain.com/page2',
      'http://www.domain.com/page3',
      'http://www.domain.com/page4',
      'http://www.domain.com/page5',
      'http://www.domain.com/page6',
      'http://www.domain.com/page7',
      'http://www.domain.com/page8',
      'http://www.domain.com/page9',
      'http://www.domain.com/page10',
      'http://www.domain.com/page11',
      'http://www.domain.com/page12'
    ],
    options = {
        stylesheets  : ['includes/cssfile.css'],
    };

uncss(files, options, function (error, output) {
    console.log(output);
});
```

Given this is the example code, I would have assumed this would be valid, but please advise if I am doing something incorrect here.

**Comment by farser** [comment]
Get a mac.. Sorry I couldn't resist.  :)

Thanks guys, this made my afternoon.
