### ISSUE TITLE
Upgrading from 0.8.1 in gulp/grunt plugins?

### ISSUE THREAD

**Issue by ben-eb** [giakki/uncss#111]
I'm just curious as to which issues need to be resolved before we can bump UnCSS to 0.9.x in our dependent modules. Has been a few months since we have locked the versions:

* https://github.com/addyosmani/grunt-uncss/issues/110
* https://github.com/ben-eb/gulp-uncss/pull/10

I for one would love to let people use glob support directly in the gulp plugin for UnCSS. :smiley:

**Comment by ben-eb** [comment]
Ready for the new version. https://github.com/ben-eb/gulp-uncss/pull/23 :smiley:

**Comment by giakki** [comment]
Cheers!
I'll try and finish 0.12 ASAP so you can both update safely ;)

**Comment by ben-eb** [comment]
@giakki Good to go?

**Comment by giakki** [comment]
:+1:
