### ISSUE TITLE
Code in IE conditionals

### ISSUE THREAD

**Issue by XhmikosR** [giakki/uncss#112]
At the moment, those seem to be removed with 0.8.1.
I can't test any newer versions, so, I'm sorry if this is already fixed.

**Comment by bjarnef** [comment]
I see this issue too.
E.g. if your right after opening body tag have the following, it removes the class `browserupgrade` from css.

```
<!--[if lt IE 8]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
```

**Comment by ArmorDarks** [comment]
I think technically it's right that uncss doesn't parse conditional comments, because, well, those are comments, they are non-existent for everything, but IE.

Though, it would be good to have option to take conditional comments into account too.

**Comment by mikelambert** [comment]
Uncss runs PhantomJS to find out what classes are used, which is basically a headless webkit instance. So unfortunately any browser-specific code won't be run/detected unless it matches webkit too. So yeah, missing IE conditionals is a bug, but given the Uncss design is not really fixable. Unless someone wants to add a headless IE rendering that can be controlled/evaluated from JS.

**Comment by RyanZim** [comment]
> Unless someone wants to add a headless IE rendering that can be controlled/evaluated from JS

Count me out! :grinning:

**Comment by jpvincent** [comment]
Hi there
A quick note about headless IE rendering : it does exist :)
http://triflejs.org/
Of course you need a windows machin to run it but it promises to follow phantomJS API, so the integration (it one really wants to) could be done

**Comment by RyanZim** [comment]
Should we consider this `wontfix`? @mikelambert @XhmikosR ?

**Comment by XhmikosR** [comment]
I guess so now that IE conditionals are basically ignored after IE 11.
