### ISSUE TITLE
Calling uncss() multiple times not working as expected.

### ISSUE THREAD

**Issue by curtisblackwell** [giakki/uncss#136]
If I call `uncss()` more than once, only one will function properly.

For the others, I either get the following error or nothing at all.

```
TypeError: Cannot read property 'stdin' of null
```

If I comment out the other calls to `uncss()`, each works on its own.

Here's my `.js` file:

``` javascript
var uncss = require('uncss'),
    fs    = require('fs');



var home = {
  files: ['http://localhost:8080'],
  filename: 'home.css'
};

var otherConfig = {
  files: ['http://localhost:8080/my-url'],
  filename: 'my-stylesheet.css'
};

var anotherConfig = {
  files: [
    'http://localhost:8080/404',
    'http://localhost:8080/some-url',
    'http://localhost:8080/some-other-url'
  ],
  filename: 'my-other-stylesheet.css'
};

writeCSS(home);
writeCSS(otherConfig);
writeCSS(anotherConfig);




/**
* Write the css output by UnCSS
* @param {object} config The config to use.
*/
function writeCSS(config) {

  config.options = { uncssrc: 'uncssrc.json' };

  uncss(config.files, config.options, function(error, output) {
    // If UnCSS threw an error, show it.
    if (error) {
      console.error('UnCSS: ' + error + '\n' + config.filename + ' not UnCSSed.');
    } else {
      // If there was no error, write the UnCSSed styles to the set file.
      fs.writeFile('dist/path/to/css/' + config.filename, output, function(error) {
        if (error) {
          // If there was an error, show it.
          console.error(error + '\n' + config.filename + ' not UnCSSed.');
        } else{
          // If there was no error, announce it.
          console.log('Success! High-five! \n' + config.filename + ' UnCSSed!!!!1');
        }
      });
    }
  });

}

```

and my `uncssrc.json`

``` json
{
  "ignore": [
    "COMMENT: Pseudo-classes",
    "active",
    "checked",
    "default",
    "dir",
    "disabled",
    "empty",
    "enabled",
    "first",
    "first-child",
    "first-of-type",
    "focus",
    "fullscreen",
    "hover",
    "in-range",
    "indeterminate",
    "invalid",
    "lang",
    "last-child",
    "last-of-type",
    "left",
    "link",
    "not",
    "nth-child",
    "nth-last-child",
    "nth-last-of-type",
    "nth-of-type",
    "only-child",
    "only-of-type",
    "optional",
    "out-of-range",
    "read-only",
    "read-write",
    "required",
    "right",
    "root",
    "scope",
    "target",
    "valid",
    "visited",

    "COMMENT: Pseudo-elements",
    "after",
    "before",
    "first-letter",
    "first-line",
    "selection",

    "COMMENT: Animations",
    ".flipInX"
  ],
  "ignoreSheets": [
    "http://fonts.googleapis.com/css?family=Amatic+SC:400,700",
    "http://fonts.googleapis.com/css?family=Open+Sans:300italic,700italic,700,300"
  ],
  "media": [
    "(max-width: 480px) and (orientation: landscape)",
    "(max-width: 767px)",
    "(min-width: 1200px)",
    "(min-width: 1721px)",
    "(min-width: 768px) and (max-width: 991px)",
    "(min-width: 768px)",
    "(min-width: 992px) and (max-width: 1199px)",
    "(min-width: 992px)",
    "screen and (max-width: 767px)",
    "screen and (min-width: 768px)"
  ],
  "timeout": 1000,
  "htmlroot": "dist"
}
```

Do you spot anything I'm doing wrong?

**Comment by craig-joseph-lucas** [comment]
@curtisblackwell can you provide your workaround please

**Comment by curtisblackwell** [comment]
@craig-joseph-lucas It's been a while since I wrote it, but I'm pretty sure it's kind of engrained into a Grunt setup I put together for [Statamic](http://statamic.com). You're free to take a look and tweak/use it, though.

[uncss.js](https://github.com/thefriendlybeasts/mr_pig/blob/master/mr_pig/uncss.js)

**Comment by craig-joseph-lucas** [comment]
Thanks I was actually looking for a solution that will work with Gulp

**Comment by curtisblackwell** [comment]
@craig-joseph-lucas Isn't Gulp also built on Node? If so, I think it should work, but I haven't dug very deep into Gulp yet ¯\_(ツ)_/¯.

**Comment by craig-joseph-lucas** [comment]
Looks like this problem was fixed for grunt-uncss. Any chance we can do the same solution for gulp-uncss

https://github.com/addyosmani/grunt-uncss/commit/af258f0b11e9c3a472b23ea68c8c9104505cf169

**Comment by craig-joseph-lucas** [comment]
Also does gulp-uncss support configuration like this

      files: {
           'tests/output.css': 'tests/index.html',
           'tests/output2.css': 'tests/index2.html',
         },

**Comment by curtisblackwell** [comment]
ooh, good to know. I'll have to try that out so I can throw out my slop.

**Comment by RyanZim** [comment]
@mikelambert Wasn't this fixed in 7a1e1cfc9532946fec1f69869c23dc785f0058c5?

Someone should also file a bug with https://github.com/addyosmani/grunt-uncss to revert https://github.com/addyosmani/grunt-uncss/commit/af258f0b11e9c3a472b23ea68c8c9104505cf169. I'd be willing to, just let me know.

**Comment by XhmikosR** [comment]
Is this fixed? If so I should revert the grunt-uncss change.

**Comment by RyanZim** [comment]
Uncss 0.15.0 no longer uses PhantomJS, so I assume this is fixed. CC: @XhmikosR

**Comment by XhmikosR** [comment]
Yeah, i already reverted this https://github.com/addyosmani/grunt-uncss/commit/cb270c5a09904cd2a928cafe2ced7bf06e55d9b7
