### ISSUE TITLE
UnCSS not properly getting CSS for a site with the Foundation framework

### ISSUE THREAD

**Issue by imolorhe** [giakki/uncss#139]
Hello, been looking into using the UnCSS tool with our current grunt workflow. After installing it and testing the tool out, some of the UI elements were broken. At first, I figured I would add them into the tool manually but that would not be feasible. I ran the grunt task specifying it to look through the entire site hoping that would fix it but didnt either. Please I need help on this as I would love to use this tool. Thanks

**Comment by ben-eb** [comment]
UnCSS doesn't support selectors that were added through page interaction; clicks, hovers, focus, form updates etc. It will only be able to analyse those selectors that were added at *runtime* using the `timeout` option. For projects using a framework such as Foundation or Bootstrap you will have to maintain an `ignore` list for classes that are added by the JS components.

I think another option is to write a layer for your functional/integration tests that can get the state of the DOM after a menu is clicked, or a form is updated, then pass all of those HTML pages through to UnCSS afterward; but that is indeed a bigger concern than an `ignore` list of selectors. :smile:

**Comment by addyosmani** [comment]
some Phantom integrations make use of a waitsFor option to delay DOM scraping until some condition or set of conditions are met. For example, a set of classes are present on specific nodes. Something like that could be explored, but it would be another layer to add in.

**Comment by ben-eb** [comment]
True, but more often that not classes will be present on DOM nodes after some user interaction. I think a good way of capturing that would be to use [casperjs](http://casperjs.org/) and get it to fill out forms, click on drop-downs etc. Then, a more accurate picture of what is being used will be shown, but also it means developing a comprehensive test suite which takes time.

I wonder if another approach such as statically analysing the JS files for things like `document.querySelector('li').classList.add('test');` or `document.getElementById('form').className = 'submitted'` might be appropriate; but if so, wouldn't that be a better standalone tool? If such a tool could find class names or ID attributes etc in JS files, then it would automatically be able to output an ignore list for UnCSS, which is the main point of contention here. But, there are problems with that too, such as dynamically created class names, or a helper function that wraps the classList API. :smiley:

I think one of the flaws of these frameworks is that they make assumptions for you which you might not think is best. Many JS components therein squash together behavioural and presentational logic in the same CSS classes; whereas for your own components you might like to separate behavioural classes out into selectors such as `.js-active`, `js-hidden`, `js-toggle` etc. Then, you can just pass an ignore regex to UnCSS which matches `.js-*`, which is much simpler.

I'm not sure if there's a simple solution for this problem.

**Comment by giakki** [comment]
Exactly what I think. :+1:

However, since frameworks are here to stay, I was actually thinking of starting a wiki here on Github listing which selectors you should ignore given a framework or script. I already have a list of some defaults I use, and adding some for Bootstrap / Foundation / Pure / Web Components would be easy.

I don't think baking this functionality into UnCSS is feasible, since their APIs change fast, and there are always new frameworks to build upon; a wiki that everyone can edit is probably the solution.

**Comment by ben-eb** [comment]
@giakki Love the wiki idea. :+1:

**Comment by imolorhe** [comment]
:+1:

**Comment by addyosmani** [comment]
Wiki idea sgtm :+1:

**Comment by XhmikosR** [comment]
While the idea seems nice, it's hard to stay up to date with all the frameworks and their JS selectors...

**Comment by imolorhe** [comment]
@XhmikosR the wiki can contain version-specific framework selectors to be ignored. Hopefully future updates to such frameworks would have a standard to how dynamically added classes are named for ease in specifying and using them.

**Comment by XhmikosR** [comment]
Again, it's not a foolproof solution. The tool should extract the selectors used.

**Comment by sagaio** [comment]
I'm trying to use this tool for a WordPress template which has it's own custom selectors, not selectors based on any particular framework. 
The wiki project would be great for some. There will still be situations where new functionality will be needed to make this great tool work. I think a universal approach is the way to go to solve this.

**Comment by imolorhe** [comment]
@XhmikosR Don't you feel the wiki project would be alright for now, especially since the tool cannot currently extract all the selectors correctly?

**Comment by XhmikosR** [comment]
It's a semi-measure. Javascript inserted selectors are so common nowadays.

**Comment by imolorhe** [comment]
@XhmikosR Well you're right about that.

**Comment by alanontheweb** [comment]
This script is amazing. I can almost use it in prod, except for this issue. Anything on the horizon for user interaction detection?

**Comment by brettdewoody** [comment]
The issue I'm seeing in Foundation is the JS-injected classes aren't being injected. For example, I'm using Foundation's `sticky` top bar. Without `uncss` Foundation should inject several classes into HTML doc - into the `body` element and the `nav` wrapper, once the user scrolls past a certain point. I'm not seeing the classes injected after running `uncss` however. 

Why would running `uncss` cause the JS-injected classes to not be injected?

**Comment by brettdewoody** [comment]
Sounds like we'll need to maintain an `ignore` list to make UnCSS work with Zurb Foundation. Here's my current `ignore` array that's working for me:

    ignore: [/^meta.foundation/, /f-topbar-fixed/, /contain-to-grid/, /sticky/, /fixed/]

The only JS module I'm using is `topbar`

Available as a Gist - https://gist.github.com/brettdewoody/ee8f235d418e8c08443b

**Comment by addyosmani** [comment]
Perhaps it's worth maintaining safe ignore lists for popular CSS/JS libraries.

**Comment by brettdewoody** [comment]
Great idea @addyosmani. Perhaps a repo with files for each CSS/JS library?

**Comment by iandanforth** [comment]
@ben-eb Are you aware who's managed to do the selenium / uncss integration? That is the road I'd like to walk.

**Comment by ben-eb** [comment]
@iandanforth Sorry, my experience with selenium is very limited. I think to pull this sort of thing off automatically you need a robust set of front-end integration tests, so the better option is probably an ignore list for your particular code base. :smile:

**Comment by RyanZim** [comment]
I got together an ignore list for bootstrap v3.3.6:
```
[/\.fade/, /\.modal/, '.affix', /\.tooltip/, /\.popover/, /\.collaps/, /\.carousel-inner/]
```

@XhmikosR Should this be in the wiki or as a separate personal gist or repo (with a link from here)?

**Comment by XhmikosR** [comment]
We could put this in README.md.

Again, I still don't think it's worth maintaining a list but I guess it's better than nothing.

**Comment by RyanZim** [comment]
@XhmikosR I question the wisdom of putting this in the README. It would work for now, but this section could get to be pretty long if you have a list for Bootstrap v3 & v4, Foundation, Materialize, ... you get the idea. It's up to you though.

**Comment by XhmikosR** [comment]
It's not my choice because personally I find this bad l. It beats the point
of uncss if we are going to ignore selectors like that.

Regardless, I will add it in the wiki and we'll see how maintained it the
page will be.

**Comment by RyanZim** [comment]
The only slightly better option I can think of is to campaign that frameworks prefix all their dynamic classes with `.js-`.

**Comment by XhmikosR** [comment]
That is not the case for Bootstrap that I can speak of.

**Comment by XhmikosR** [comment]
@RyanZim: https://github.com/giakki/uncss/wiki/Using-uncss-with-Bootstrap

**Comment by crico** [comment]
Do you know any ignore list for bootstrap v2?

**Comment by RyanZim** [comment]
No; If you make one, we might post it on the wiki.

**Comment by RyanZim** [comment]
Closing for lack of action; feel free to add additional wiki entries for common framworks.
