### ISSUE TITLE
[io.js] Installation stuck at copying extracted PhantomJS files

### ISSUE THREAD

**Issue by gsklee** [giakki/uncss#142]
I've tried to install UnCSS on a few devboxes and every first attempt on installing the package would all stuck at a certain point:

```
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...
  [================================--------] 81% 0.0s
Received 12854K total.
Extracting tar contents (via spawned process)
Removing /home/kay/Projects/yoker/node_modules/gulp-uncss/node_modules/uncss/node_modules/phantomjs/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2-extract-1422171886267/phantomjs-1.9.8-linux-x86_64 -> /home/kay/Projects/yoker/node_modules/gulp-uncss/node_modules/uncss/node_modules/phantomjs/lib/phantom
```

Then it would always stuck. I was able to `ctrl+C` and rerun the installation to get it through, but if it goes on like this there will be troubles deploying the project to production server in an automatic manner.

**Comment by gsklee** [comment]
Confirmed that this is an io.js specific problem; didn't happen when I used the latest node unstable version.

**Comment by ben-eb** [comment]
This issue https://github.com/Medium/phantomjs/issues/275#issuecomment-70879593 seems to point to `ncp` being the culprit; so yes, indeed this does look like an io.js issue and not something we can fix in UnCSS.

**Comment by gsklee** [comment]
Ok cool, thanks!
