### ISSUE TITLE
regex breaking the uncssrc json?

### ISSUE THREAD

**Issue by glenn-smith** [giakki/uncss#146]
I'm using 0.12.0, and when I try to add some regex to the ignore array, I get "SyntaxError: UnCSS: uncssrc file is invalid JSON."
The uncssrc file is like this:
```
{
  "ignore": [
      "/\.success-page.*/",
      ".tip",
      ".twrap",
      ".reveal-modal"
  ]
}
```

I have tried that first line with and without the forward slashes.  Thoughts?  Cheers!

**Comment by giakki** [comment]
This is a limitation with the uncssrc format: `"/\.success-page.*/"` is not valid JSON, while `"/\\.success-page.*/"` is.

We might change this behavior in the future, so that you can specify regexps directly, without the use of quotes!

**Comment by glenn-smith** [comment]
Ahh, ok. Many thanks!
