### ISSUE TITLE
Update css to 2.2.0?

### ISSUE THREAD

**Issue by XhmikosR** [giakki/uncss#151]
@giakki: there's a new css version https://github.com/reworkcss/css/compare/v2.1.0...v2.2.0

I wonder if it has any of our issues fixed?

**Comment by XhmikosR** [comment]
@giakki: I still get the same error we got with 2.1.0.

```
Running "uncss:dist" (uncss) task
Fatal error: uncss/node_modules/css: unable to parse undefined: Maximum call stack size exceeded
```

Have you tried reporting the issue upstream?

**Comment by XhmikosR** [comment]
Hmm https://github.com/reworkcss/css/issues/56

So I guess we should try PostCSS.

**Comment by ben-eb** [comment]
:+1: for PostCSS.

**Comment by XhmikosR** [comment]
@ben-eb: have you tried making the switch? Not sure how complex it will be...

**Comment by ben-eb** [comment]
@XhmikosR I'm actually using PostCSS for another project; the parser is up to twice as fast as the css module, and its way of handling plugins is done in a very modular way. From my initial experiments with it, it seems like it would be a good fit, especially as they are adding support for asynchronous transformations with promises.

**Comment by XhmikosR** [comment]
I meant if you tried switching to it for uncss :)

I'm all for it especially since it is way more actively developed.

**Comment by ben-eb** [comment]
Ahh, ok. I haven't no, been really busy with university stuff; would like to contribute a bit more to this project but it's hard finding the time. :smile:

But I can't imagine this being too difficult to develop, especially now that we have a good suite of tests.
