### ISSUE TITLE
phtml files

### ISSUE THREAD

**Issue by cortopy** [giakki/uncss#154]
Does uncss work with phtml files? I'm using it with gulp and it doesn't seem to recognise any of my local files. I'm guessing it's not possible for uncss/PhantomJS to render files so it would be giving errors even if files where accepted

The problem is that when giving pages on a localhost:8080, uncss works fine but it's unable to track css classes used in, for example, a checkout page (as there's no page added to cart for PhantomJS).

So if phtml can't be used, would it be possible to use CasperJS with uncss/phnatomjs to create possible scenarios?

**Comment by phlorie** [comment]
Hi
This is a question I am also interested about.
With frameworks and CMS these days, it is very rare to have a big project with just static HTML pages. It is common to use includes.
Every loaded CSS is in a file containing only the header and that file is loaded for all the pages. There is no CSS classes in the file containing the reference to the CSS files, even for a simple CMS like Wordpress.
I'd like to know if there is a solution in that situation. A need would not only be to remove unused classes but also duplicated code or what has been overwritten. Is that something uncss does?
Thanks in advance.

**Comment by bezoerb** [comment]
@phlorie you could use [`php2html`](https://github.com/bezoerb/php2html) to generate static HTML files for a specific set of routes in your local Wordpress project. You could then use the generated files as source for uncss

**Comment by cortopy** [comment]
@phlorie would that work with phtml though? I've just tried php2html using gulp and it only gives error.

**Comment by ben-eb** [comment]
@cortopy @phlorie You are correct in your assumptions about UnCSS. It has no concept of being able to track a user's journey through a website, it can only load a page and calculate what styles are used *at runtime*. Therefore, for richer experiences which involve managing session data & logged in and logged out states, you have to feed UnCSS static files that contain all of that state.

You could do this in the case of a CMS by getting a spider to crawl your site and dump the HTML output into a directory, then have UnCSS analyse the files for anything unused. And in the case of some other dynamic content, it is possible to use something like CasperJS to interact with your site and write a HTML file at each state - load page, capture, do a form action, capture, etc.

I admit that this isn't ideal, and hope that once the unused reporter is finished, then people can be more aware of what classes UnCSS is removing, and then be able to make better decisions about how to manage their ignore lists.

**Comment by bezoerb** [comment]
@cortopy what kind of errors? Would you mind adding an issue over at [`gulp-php2html`](https://github.com/bezoerb/gulp-php2html)?

**Comment by RyanZim** [comment]
@mikelambert Any reason to keep open?

**Comment by mikelambert** [comment]
Just to followup with the original poster's question at the end. There is no integration with CasperJS inside uncss, but it would be possible to build something like that. Alternately, you could probably use CasperJS to dump out versions of the HTML after every modification, and feed those files to uncss, which would accomplish the same thing (but without needing to dig in and modify any of the uncss internals, or tie uncss to casperjs)
