### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by szepeviktor** [giakki/uncss#155]
Is donation possible?

**Comment by giakki** [comment]
Thanks for the support!
I have a Flattr thing over at https://flattr.com/thing/2388296

**Comment by szepeviktor** [comment]
@giakki When do you receive the €10?

**Comment by szepeviktor** [comment]
> [On the 10th date of the following month](https://flattr.com/howflattrworks)

**Comment by giakki** [comment]
Cheers!
Thanks you again! :)
