### ISSUE TITLE
Outputs errors on stdout

### ISSUE THREAD

**Issue by andrewmoise** [giakki/uncss#157]
When I run uncss on my page, I get some errors:

```
SyntaxError: Parse error
ReferenceError: Can't find variable: jQuery
```

... and so on. The problem is that when run according to the recommended usage (`uncss /some/html > reduced.css`), the errors get written into the .css file and I don't see them (and it silently generates a busted .css file).

I don't know if it's possible for the uncss binary to write to stderr; if it is that would be better. If that's not possible, another alternative would be to have an option for what the output file should be, and to have the help text recommend people use the output file option instead of redirecting output.

Thanks in advance for your help!

**Comment by XhmikosR** [comment]
For that specific error, try using paths like `/foo/bar.js` instead of `foo/bar.js`.

For the question itself, wait for @giakki.

**Comment by giakki** [comment]
Thanks for the report, it looks like the errors were indeed written to stdout by default!
