### ISSUE TITLE
Ignore option not working as expected

### ISSUE THREAD

**Issue by penrillian-barry** [giakki/uncss#161]
I have a page showing a list of items. At runtime, each row has either an 'odd' or an 'even' css class applied. This is the relevant css:

#fileItemWrapper .even,
#fileItemWrapper .odd {
  height: 80px;
  width: 95%;
}

#fileItemWrapper .even {
  background-color: #eee;
}

I.e. the list items have colours alternating between white and #eee. The .even and .odd classes never appear in my html files, so I added then to my uncss ignore list: 
        options: {
            ignore: ['.odd', '.even']
        }

However, the css was still deleted by uncss. To get the desired behaviour, I had to set my ignore list like so:
options: {
            ignore: ['#fileItemWrapper .odd', '#fileItemWrapper .even']
        }

Is this the intended behaviour? My concern is that I am working on a huge web project and there may be many similar occurrences of this situation in the codebase.

Thanks,
Barry

**Comment by ben-eb** [comment]
This is the intended behaviour - if you pass a string, UnCSS will ignore selectors that match exactly that string. However, if you use a regex instead, you can be less specific:

```js
options: {
    ignore: [
        /\.(odd|even)/
    ]
}
```

**Comment by penrillian-barry** [comment]
Thanks Ben. So I could string all of my classes into a single regex like this:
options: {
    ignore: [
        /\.(odd|even|yes|no|otherClass|andAnotherClass)/
    ]
}

Thanks,
Barry

**Comment by ben-eb** [comment]
Yes, but you can also pass an array of regexes too. :smile:

**Comment by penrillian-barry** [comment]
Thanks Ben. I now have it working the way I want :-)

**Comment by ben-eb** [comment]
Awesome! :+1:
