### ISSUE TITLE
uncss on local wordpress site?

### ISSUE THREAD

**Issue by dingo-d** [giakki/uncss#162]
I have a site I'm developing on a local server, and I tried running uncss from command prompt with 

`uncss \\my.server\my-folder\theme-folder > style.css`

`But I get Error UnCSS: no HTML files found`.

I have wordpress on server as well as HTML sites, and I tried to run it for wp and html sites as well. Same thing happens. Is there some kind of settings I'm missing? The server is windows server 2012, I installed uncss via node.js.

Is it possible to scan the wordpress site with uncss?

**Comment by digiltd** [comment]
Here is a great guide about WordPress and uncss:
https://gladdy.uk/blog/2014/04/13/using-uncss-and-grunt-uncss-with-wordpress/

**Comment by dingo-d** [comment]
Thanks, I'll check this out :)

**Comment by digiltd** [comment]
Though I had more luck ripping my local site with httrack, and then running the task on the exported html.

**Comment by RyanZim** [comment]
@mikelambert Any reason to keep this open?
