### ISSUE TITLE
Cyrillic paths regression

### ISSUE THREAD

**Issue by ArmorDarks** [giakki/uncss#163]
Hi

It seems that some of newer versions introduced regression in handling of cyrillic paths.

If any path to htmls will contain cyrillic characters, task will simply stuck forever on that stage:

```
Running "uncss:build" (uncss) task
```

I'm not sure which version exactly introduced that issue, but last time I've used grunt-uncss `0.3.8` with version of uncss `0.8.1` — everything worked fine. Seems that regression was introduced somewhere after `0.10.0`.

Reverting to  grunt-uncss `0.3.8` fixes issue.

**Comment by ArmorDarks** [comment]
Tested with `0.12.1` — issue still persists.

**Comment by MrHyde** [comment]
Same here, just tested it with lastest version and task just stuck, which makes it unusable on projects with Cyrillic path

**Comment by ArmorDarks** [comment]
Seems that issue has been resolved in `0.5.1`

**Comment by RyanZim** [comment]
@ArmorDarks If this is indeed resolved, please close this.
