### ISSUE TITLE
Handling of `//` protocol resolving

### ISSUE THREAD

**Issue by ArmorDarks** [giakki/uncss#164]
Hi

Seems that similar to https://github.com/addyosmani/grunt-uncss/issues/13 error appeared again in `grunt-uncss` 0.4.0 and higher versions, which definitely has something to do with `uncss` itself:

``` coffee
###
Uncss
https://github.com/addyosmani/grunt-uncss
Remove unused CSS
###
module.exports = ->
  @config 'uncss',
    build:
      options:
        htmlroot: 'build'
      files: [
        src: 'build/{,**/}*.html'
        dest: build/assets/styles/style.tidy.css'
      ]
```

```html
	<!-- Fonts -->
	<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,300,600,700&amp;subset=latin,cyrillic">
```

results in:
![39d5n5](https://cloud.githubusercontent.com/assets/4460311/6970136/3160d156-d97c-11e4-9fab-c86080431367.png)

Please note that there is nowhere can be found path `build\css` in project or microtemplate's variables, while actuals project's css stored in `build\assets\styles`

Using of full protocol name `http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,300,600,700&amp;subset=latin,cyrillic` fixes that issue, but it should work with `//` too I guess

In `grunt-uncss` 0.3.8, which works with lower than `0.10.0` uncss version all works fine

**Comment by ArmorDarks** [comment]
Tested with `0.12.1` — issue still persists.

**Comment by MrHyde** [comment]
Just tested it with lastes version, problem is still present. Any comment on this?

**Comment by addyosmani** [comment]
Confirming this is still an issue.

**Comment by XhmikosR** [comment]
Is this still the case with the latest release?

**Comment by mrhyde** [comment]
Upgrading to latest release gets me `Fatal error: write EPIPE` error.

**Comment by RyanZim** [comment]
@ArmorDarks @addyosmani Is this still an issue? Is anyone using `//` protocols anymore?

**Comment by mrhyde** [comment]
Seems like issue was resolved. At least I'm not getting any problems with `//`

**Comment by RyanZim** [comment]
@mikelambert Can you close this?
