### ISSUE TITLE
error while loading shared libraries: libfontconfig.so.1

### ISSUE THREAD

**Issue by Jasmine-Lognnes** [giakki/uncss#165]
On Fedora 21:

```
bash-4.3# uncss google.com                 
/usr/lib/node_modules/uncss/node_modules/phridge/node_modules/phantomjs/lib/phantom/bin/phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory

/usr/lib/node_modules/uncss/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                                 ^
Error: /usr/lib/node_modules/uncss/node_modules/phridge/node_modules/phantomjs/lib/phantom/bin/phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory

    at Socket.onStderr (/usr/lib/node_modules/uncss/node_modules/phridge/lib/spawn.js:79:28)
    at Socket.emit (events.js:117:20)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at Pipe.onread (net.js:529:21)
```

In ran the following the advance to sure dependencies were meet
```
yum install -y bzip2 tar npm nodejs-inherits.noarch fontconfig-2.11.1-5.fc21.i686
npm install -g inherits
npm install -g uncss
```

**Comment by gpapin** [comment]
I have the same issue here, any update on how to fix it ?

**Comment by uglymunky** [comment]
I just came across this while dealing with this problem on an unrelated project.  Not sure if this helps but the solution proposed [here](https://github.com/ariya/phantomjs/issues/10904) did the trick for me.

basically, there's a hidden dependency and you can install it with:

```
> sudo apt-get install libfontconfig
```

**Comment by Awk34** [comment]
Hmmm same, thanks for the info @uglymunky

**Comment by jer0dh** [comment]
Same problem here.  @uglymunky solution is the answer!  Thanks

**Comment by piyush-mukati** [comment]
thanks @uglymunky 
"sudo apt-get install libfontconfig" is working for me too.

**Comment by DaleCox** [comment]
Thanks @uglymunky your solution solved my problem as well.

**Comment by XhmikosR** [comment]
Closing since this isn't directly related to uncss but dependency related. Feel free to make a PR to add the info to README.md if it's still valid in the latest release.

**Comment by yogieputra8** [comment]
@uglymunky mate, you saved my day! thank you 🍺

**Comment by qwertyI** [comment]
@uglymunky 
it's work for me, thanks.

**Comment by suprix** [comment]
@uglymunky Thanks it worked :DD

**Comment by lioncin** [comment]
apt-get install libfontconfig 
is very good!!!
