### ISSUE TITLE
Error: Fontconfig warning: ignoring C.UTF-8: not a valid language tag

### ISSUE THREAD

**Issue by CelticParser** [giakki/uncss#166]
Hi,  I can't figure out how to fix this one.  I get the error via Gulp, Grunt and just plan uncss.  This could be a server issue?? If so, where do I look to resolve the error. Thnx

**Comment by mathiasleroy** [comment]
I have the same error on cloud9

    d@html5:~/workspace/imb $ grunt uncss
    Running "uncss:dist" (uncss) task
    Fontconfig warning: ignoring C.UTF-8: not a valid language tag
    Fatal error: Fontconfig warning: ignoring C.UTF-8: not a valid language tag
    d@html5:~/workspace/imb $

**Comment by fouadhjiyer** [comment]
Hi,

Have you tried to type the following in the "terminal screen":
LC_ALL=C

I executed following "locale -a" and it showed me a list of all the fonts I could use then I selected "C".
So executed LC_ALL=C in the terminal screen and afterwards I could execute the command grunt uncss.

Good luck!

Kind Regards,
Fouad

**Comment by edusis** [comment]
@fouadhjiyer thanks thats works for me.

**Comment by RyanZim** [comment]
@CelticParser Is this still an issue for you?

**Comment by CelticParser** [comment]
Sorry, I missed this one; 

Running `$ LC_ALL=C` did the trick.

**Comment by DevelopSmith** [comment]
The `LC_ALL=C` fixed the problem. THANKS!

**Comment by moschel26** [comment]
@DevelopSmith Maybe you can help this question :  https://stackoverflow.com/questions/51947226/how-can-i-install-gitextensions-in-mac-os
