### ISSUE TITLE
Parse template files (.php)

### ISSUE THREAD

**Issue by IngwiePhoenix** [giakki/uncss#168]
I am using the Yii framework and would like to run UnCSS over all my templates. I know that UnCSS wants to use PhantomJS in order to get an idea of the output, but isn't there a way to support templates?

Kind regards, Ingwie

**Comment by Rask** [comment]
+1

**Comment by AlexDubstone** [comment]
+1

**Comment by YongX** [comment]
+1

**Comment by ben-eb** [comment]
Your server can already compile PHP templates into HTML, quicker and better than if someone were to bake this into UnCSS itself. UnCSS should not be responsible for server side compilation; if it were, why would it stop at PHP? What about Jade? Slim? Liquid? Twig? And countless others?

You already have a web server that can render out these languages. So, let it run on a local port and have UnCSS get the rendered HTML from those pages.

**Comment by bezoerb** [comment]
You could also use [`php2html`](https://github.com/bezoerb/php2html) to compile your templates into HTML before uncss does it's work if you don't have a local web server available. You'll just need the `php-cgi` executable available in your PATH

**Comment by replete** [comment]
This has nothing to do with UnCSS IMO.

Your best chances are to use a build system like `[Gulp](http://www.gulpjs.com)` with a PHP connect plugin like [this](https://www.npmjs.com/package/gulp-connect-php)

I wish most of the requests on UnCSS were about working towards the biggest problem - missing essential classes!

**Comment by RyanZim** [comment]
@mikelambert Any reason to keep this open?
