### ISSUE TITLE
Add support for sourcemaps

### ISSUE THREAD

**Issue by zeorin** [giakki/uncss#172]
I think it would be a great feature if uncss could create a sourcemap for it's output.

Full support would include:
* being able to parse previous sourcemap
    * either inline or separate file
    * either with sourcesContent or without
* generate sourcemap
    * either inline or separate file
    * either with sourcesContent or without

I think uncss is great, but I'm currently not using it because of a lack of sourcemap support.

**Comment by ben-eb** [comment]
This could be achieved easily with a [refactor based on PostCSS](https://github.com/giakki/uncss/issues/153). I still don't currently have the time to work on this.

**Comment by Graham42** [comment]
+1 I also can't use this module unless there is sourcemap support

**Comment by RyanZim** [comment]
Fixed in https://github.com/giakki/uncss/pull/214. Please close.
