### ISSUE TITLE
Calling uncss() multiple times still not working as expected.

### ISSUE THREAD

**Issue by signumcode** [giakki/uncss#174]
Hello, I'm having trouble running uncss, Only the first call finishes successfully.
Same issue as this one https://github.com/giakki/uncss/issues/136

**Comment by ben-eb** [comment]
Please don't open a new issue referencing an old one. You can already see that the issue has not been solved.

**Comment by craig-joseph-lucas** [comment]
Was there a resolution

**Comment by RyanZim** [comment]
@mikelambert Can you close this as per @ben-eb?
