### ISSUE TITLE
Using PhantomJS settings, viewportSize, and others

### ISSUE THREAD

**Issue by obihill** [giakki/uncss#176]
Hi,

Great work on this node package. I use [gulp-uncss](https://github.com/ben-eb/gulp-uncss) and initially posted this issue there without realizing this was the mother-ship.

I was wondering if if was possible to use PhantomJS settings (e.g. userAgent) and viewportSize? And perhaps other options as well. The reason I think this would be useful is for mimicking mobile devices, especially to cope with situations where a different CSS file is loaded based on device classification.

Thanks.

**Comment by mikeya** [comment]
It'd be nice to have the ability to send javascript event to phantomJS to show dynamically generated content that uncss would otherwise miss.

**Comment by 8thnote** [comment]
+1 to both of the prior suggestions here, especially obihill's. I'm needing this feature as I write this. Hope to hear something soon on how I could modify my gulp task so it works only on the mobile version of the site in localhost. It's unfortunately not a responsive site I'm dealing with. Thanks in advance for any help. Also, great work on this project so far! Very exciting stuff!

**Comment by RyanZim** [comment]
X-Ref https://github.com/giakki/uncss/issues/186. What do you think would be best @mikelambert?

**Comment by mikelambert** [comment]
I have nothing further to add beyond what I said in #222 , "if PhantomJS supports it, then I assume it's just a matter of making an option that plumbs it all the way down to our use of the PhantomJS API" If someone wants to do that via the route proposed in #186, all the better, but I have no time to design or build such features myself, as they are not relevant for my personal use of uncss.

**Comment by RyanZim** [comment]
@mikelambert should we close one of these issues?

**Comment by RyanZim** [comment]
uncss 0.15.0 no longer uses PhantomJS, so closing. Feel free to open any new feature requests for the jsdom versions. Also see https://github.com/giakki/uncss/issues/323
