### ISSUE TITLE
Error on 404 css file, quits early

### ISSUE THREAD

**Issue by crazy4groovy** [giakki/uncss#183]
``` BASH
$ uncss http://www.ae911truth.org > C:\ae.css

Error: uncss/node_modules/css: unable to parse http://www.ae911truth.org/templates/theme1898/css/acm.css :
property missing ':' near line 9:8
        4:        <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-gb" lang="en-gb" dir="ltr">
        5:        <head>
        6:        <title>404 - Error: 404</title>
        7:        <script type="text/javascript">
        8:        //<![CDATA[
        9:     -> try{if (
        10:        //]]>
        11:        </script>
        12:        <link rel="stylesheet" href="/templates/theme1898/css/bootstrap.css" type="text/css"/>
        13:        <link rel="stylesheet" href="/templates/theme1898/css/default.css" type="text/css"/>
        14:        <link rel="stylesheet" href="/templates/theme1898/css/template.css" type="text/css"/>

    at error (c:\Users\solsen\AppData\Roaming\npm\node_modules\uncss\node_modules\css\node_modules\css-parse\index.js:57:15)
```

Note the `<link rel="stylesheet" href="http://www.ae911truth.org//templates/theme1898/css/acm.css" type="text/css" />` is not a valid URL.

Ideally it would continue on, stripping whatever it _can_ find.

**Comment by RyanZim** [comment]
@XhmikosR what do you think?

A 404 is an error-worthy IMO. I don't think failing silently (or attempting to `console.log`) is a good idea.

**Comment by RyanZim** [comment]
@XhmikosR ping?

**Comment by crazy4groovy** [comment]
IMHO it's log worthy, not error. 

Browsers can roll with it.. why not this tool?

**Comment by RyanZim** [comment]
@crazy4groovy I tend to shy away from libraries using `console` at all unless they are throwing an error. Is there a specific use-case for _needing_ to process a 404?

**Comment by crazy4groovy** [comment]
@RyanZim Thanks, I appreciate your concern. For libraries I agree, they should never `console.log` (except debug). But I think for a cli it's perfectly reasonable to `console.log`/`println`/`stdout`/etc. any useful feedback/results of the execution. Since there's a human on the other side.

**Comment by RyanZim** [comment]
In most cases I would agree with you; however, with the new capabilities of using uncss as a PostCSS plugin, is uncss a cli or library?

Some people will probably use uncss by calling grunt, to call grunt-postcss, to call postcss, to call uncss.

**Comment by RyanZim** [comment]
Another reason I oppose using `console` is the difficulty of testing without interlacing the test results with logging.

When all is said and done, the fact remains that I like the existing functionality, and you would prefer changes. I'll leave the final decision to @XhmikosR & @mikelambert.

**Comment by RyanZim** [comment]
@XhmikosR ping?

**Comment by crazy4groovy** [comment]
@RyanZim I could see the cli as catching the library errors and consoling them out, whereas the other tools you mention may which to throw (/not catch) any library errors.

**Comment by RyanZim** [comment]
I have nothing more to say on this.

> I'll leave the final decision to @XhmikosR & @mikelambert.

**Comment by RyanZim** [comment]
One more thing I came across: https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#32-use-resultwarn-for-warnings. That pretty well outlaws `console`.

CC: @mikelambert

**Comment by RyanZim** [comment]
Going to close this as `wontfix`; if someone feels strongly otherwise, feel free to reopen.
