### ISSUE TITLE
Pass arbitrary command line parameters to PhantomJS

### ISSUE THREAD

**Issue by chrisbautista** [giakki/uncss#186]
Hi

Great job with UnCSS!

Recommendation to pass arbitrary commandline parameters to PhantomJS e.g.

http://phantomjs.org/api/command-line.html

This parameters could solve a lot of issues including turning off cross domain checking or running PhantomJS in proxy mode.

Any hints?

Warm Regards

Chris

**Comment by XhmikosR** [comment]
We no longer use phantom.js.
