### ISSUE TITLE
UnCSS importing external stylesheets

### ISSUE THREAD

**Issue by jdahdah** [giakki/uncss#187]
We're using `@import` to include a few external font stylesheets via `//` paths within our main.css stylesheet. It needs to be agnostic of http/https since we have pages running on both protocols and sometimes have to run external applications within the site that reference our stylesheet. We're running UnCSS on build via [gulp-uncss](https://github.com/ben-eb/gulp-uncss), which seems to be following the paths and then inlining the content of those external stylesheets into main.css, something that I assume it shouldn't be doing. This brings up some legal issues, because we're using licensed fonts and UnCSS is removing the counter our font host requires us to integrate (it works via calling an empty css file via `@import`). Any way to prevent this from happening (apart from restructuring our css) or would this be a bug?

**Comment by XhmikosR** [comment]
Is this still the case with the latest release?

**Comment by jdahdah** [comment]
I just found the string in the exported build, so it would appear that UnCSS is no longer doing this. Cheers!
