### ISSUE TITLE
Parsing files that are not .html

### ISSUE THREAD

**Issue by DevBlaaast** [giakki/uncss#189]
Hi guys, thanks for this tool it is really helpful to us.

However I have an issue : I would like to be able to parse files that are not .html while looking for classes to uncss.

Thanks for any help you could provide.

**Comment by SuperMiMi** [comment]
+1

**Comment by fionnayao** [comment]
What type of files are you trying to pass through UnCSS? I don't think UnCSS performs server side compilation. You might have to use a web server to render HTML, then run UnCSS on them :)

**Comment by DevBlaaast** [comment]
@fionnayao I want to do it on .hbs files. I actually use gulp to compile them right now, but I need the html files to be created after the css task.
I need both the css files to be created with a md5 hash (for cache busting) and also to be uncss-ed. The thing is that I write the md5-hashed css files inside the html files, so I cannot run uncss after the html files are created :)

**Comment by adrien-constant** [comment]
Support for razor files (.cshtml) would be great too :)

**Comment by bjarnef** [comment]
I am using [gulp-uncss](https://www.npmjs.com/package/gulp-uncss) view razor / MVC views. I use it in an Umbraco install where the files are located in `/Views/ and `/Views/Partials/`folders.

It works with the following:

```
.pipe(plugins.uncss({
       html: ['./Views/*.cshtml', './Views/Partials/*.cshtml'],
       ignore: ['footer .copyright', 'footer .copyright a']
}))
```

In /View/Partials/Copyright.cshtml I have the following, but it removes css for copyright class if I not add it to the ignore list.

```
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
<div class="copyright">
	<div class="container">
		<span><a target="_blank" href="http://www.oerskovweb.dk/">Umbraco & Webdesign | My Company</a></span>
	</div>
</div>
```

Furthermore it doesn't seem to like specifying `**`in path to .cshtml files.

`html: ['./Views/*.cshtml', './Views/**/*.cshtml']`
which returns `Cannot communicate with PhantomJS process: Unknown reason`

If I just pass in `html: ['./Views/Partials/Copyright.cshtml']` it also removes styles for the class.

**Comment by mikelambert** [comment]
UnCSS operates on fully-rendered pages, asking the Phantom browser for what CSS classes are used.

You cannot pass in partial-pages templates, as they are not well-formed HTML, and may or may not work depending on how "partial" they are, and what Phantom is willing to accept and render. If you render a complete page and pass that in to UnCSS, does it correctly retain the 'copyright' class?

**Comment by mikelambert** [comment]
@DevBlaaast , can you generate the HTML pointing at an external CSS file, run the UnCSS on that? Then integrate the resulting CSS and HTML at server render time. That's what I've done in a case like that (AMP HTML requires that CSS be inlined in the HTML.)

**Comment by bjarnef** [comment]
Well, it works fine for the other partials view - I am aware that some views has dynamic content, but can be ignored in those cases. But it is strange it it just Copyright.cshtml where it fails, which just content static html. In a Footer.cshtml in same folder it does retain the classes in css.

**Comment by DevBlaaast** [comment]
@mikelambert yes that's what I do too

**Comment by mikelambert** [comment]
@bjarnef Ah okay. Any idea what is different between Copyright and Footer? I'm sure you can do some debugging to figure it out (if the 'copyright' rule is in Footer.cshtml, does it work? What about putting footer css classes in Copyright.cshtml? Are the css classes defined differently in CSS, ie is one a child/descendent/nested selector that might be dependent on embedding?)

As for "matching all pages from root", I'm not sure how it would automatically know all the valid pages/servlets on your website? You could throw in some basic webcrawler and feed the resulting URLs in to UnCSS, or maybe autogenerate them with something akin to this pseudocode glob('./views/.cshtml').map(function(filename) {'http://localhost:50500/' + filename})?

**Comment by bjarnef** [comment]
@mikelambert Copyright.chtml is just the last bar here:
![image](https://cloud.githubusercontent.com/assets/2919859/14557992/3f6ca21c-0300-11e6-8dcf-60cd4ff08843.png)

Footer.cshtml
```
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	var site = CurrentPage.Site();
	<footer>
		<div class="contact-info">
			<div class="container">
				<span>@site.companyName</span>
				<span>@site.address</span>
				<span>@site.ZipCity</span>
				<span>Tlf: @site.phoneNumber</span>
				<span><a href="mailto:@site.email">@site.email</a></span>
			</div>
		</div>
		@Html.Partial("Copyright")
	</footer>
}
```

Copyright.chtml:
```
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
<div class="copyright">
    <div class="container">
        <span><a target="_blank" href="http://www.mycompany.dk/">Umbraco & Webdesign | My Company</a></span>
    </div>
</div>
```

Funny enough it does work if I just copy markup from Copyright to Footer:
```
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	var site = CurrentPage.Site();
	<footer>
		<div class="contact-info">
			<div class="container">
				<span>@site.companyName</span>
				<span>@site.address</span>
				<span>@site.ZipCity</span>
				<span>Tlf: @site.phoneNumber</span>
				<span><a href="mailto:@site.email">@site.email</a></span>
			</div>
		</div>
		<div class="copyright">
			<div class="container">
				<span><a target="_blank" href="http://www.mycompany.dk/">Umbraco & Webdesign | My Company</a></span>
			</div>
		</div>
	</footer>
}
```

but Footer is also added to Master.cshtml like this without issues:
```
@Html.Partial("Menu")
@RenderBody()
@Html.Partial("Footer")
```

**Comment by mikelambert** [comment]
"Funny enough it does work if I just copy markup from Copyright to Footer" should be a very big clue as to what is going wrong for you. What is special about Copyright that makes it different from Footer? (Hint: Check your filenames.)

**Comment by bjarnef** [comment]
I can't see what the issue is with the file names as it is working fine without running uncss.
It includes Copyright partial view in Footer partial view.
And all styling in included in same less file, which is compiled before running uncss.

**Comment by mikelambert** [comment]
They have two different extensions, but your glob you pass to UnCSS only includes one of them.

**Comment by bjarnef** [comment]
Sorry, it was a typo.. both are MVC partial views, so `.cshtml` 

I have also passed the direct path to Copyright.cshtml, but with same result.
`html: ['./Views/Partials/Copyright.cshtml']`

**Comment by RyanZim** [comment]
@bjarnef Perhaps PhantomJS doesn't parse css classes directly after `@`.

Footer:
```
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    var site = CurrentPage.Site();
    <footer>
        <div class="contact-info">
...
```

Copyright:
```
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
<div class="copyright">
...
```

Anyhow, uncss can't support parsing server-side code. You'd be best off precompiling it to HTML and running that through uncss.
