### ISSUE TITLE
Grunt-uncss settings for nested folders and root-relative links

### ISSUE THREAD

**Issue by supervova** [giakki/uncss#190]
**Thanks for unCSS. Please help me rewrite working but ugly settings of grunt-task**.
I've tried using htmlroot and csspath options but w/o results.

Project structure (yeoman webapp)
app
&nbsp;&nbsp;css
&nbsp;&nbsp;img
&nbsp;&nbsp;js
&nbsp;&nbsp;section1
&nbsp;&nbsp;&nbsp;&nbsp;subsection
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;index.html
dist

In HTML I use root-relative paths
`<link rel="stylesheet" href="/css/main.css">`

Settings in Gruntfile.js

```javascript
var config = {
  app: 'app',
  dist: 'dist',
  mainCSS: '/css/main.css',
  mainCSSpathPrefix: '../..',
  targetHTML: '/section1/subsection/index.html'
};

//-----------------------------------------------

uncss: {
  dist: {
    options: {
      ignore: [/dropdown-menu/, /\.collapsing/, /\.collapse/],
      stylesheets:  ['<%= config.mainCSSpathPrefix %><%= config.mainCSS %>']
    },
    files: {
      '<%= config.app %><%= config.mainCSS %>': ['<%= config.app %><%= config.targetHTML %>']
    }
  }
}
```
I don't like using relative path prefix. I think this is a weak and obviously not-DRY solution. Maybe someone help me w/ right one? 10x in advance

**Comment by RyanZim** [comment]
`htmlroot` should work.

**Comment by RyanZim** [comment]
@supervova What happens when you use `htmlroot`? Are there error messages?

**Comment by RyanZim** [comment]
@mikelambert It seems this issue has been abandoned by the OP.

**Comment by RyanZim** [comment]
@mikelambert ping?
