### ISSUE TITLE
Ignoring JavaScript blocks

### ISSUE THREAD

**Issue by ourmaninamsterdam** [giakki/uncss#191]
I'm using uncss via Grunt. The page I'm producing is  iframed. In the top of the iframed page I have a script that redirects users if they hit the iframe URL directly:

```html
<head>
<script>if(window.self === window.top){ window.location.href = 'http://www.foo.com/iframe-parent'; }</script>
</head>
```
This works fine via a browser. However, uncss also runs this script, which obviously causes problems with the output.

Is there anyway to ignore `<script>` blocks? I've tried adding an `id` to the `<script id="iframe">` block and ignoring it via the config: 

```javascript
 uncss: {
      options: {
        ignore: [
          /[#]{1}iframe/
        ],
      },
```

I've also tried moving the `<script>` into a `<div>` within  `<body>` but I get the same output issues.

**Comment by ourmaninamsterdam** [comment]
I realise now that the use of `ignore` is to actually ignore selectors within the CSS file, not within the HTML. I should have read the docs nore thoroughly.

Anyway, having an option to ignore a block of HTML when running the page through Phantom would be great.

**Comment by RyanZim** [comment]
I'm not sure how we would do this. For your case, you could add user-agent sniffing for phantomJS to your js.

**Comment by RyanZim** [comment]
@XhmikosR What do you think of this feature?

**Comment by XhmikosR** [comment]
I don't think this would help. If one is using the ignore option properly, there's no need for this.

**Comment by RyanZim** [comment]
OK, just wondered. If you're not going to implement this, might as well close this.

**Comment by mikelambert** [comment]
I think there may be a legitimate claim that uncss does not work with well with frames. Maybe that's worth a tracking bug, though this one isn't directly about that.

Independently, ignoring JS Isn't a feature I think is really workable to support. One could achieve it I'm this case by requesting a URL like "/blah#skip-parent", and check for that in the JS to avoid the parent redirect.

**Comment by RyanZim** [comment]
I agree with @mikelambert. Of course, as I said earlier, you could also do UA sniffing for PhantomJS in your JS.
