### ISSUE TITLE
Throws error when 'requestAnimationFrame' is on page.

### ISSUE THREAD

**Issue by hellsan631** [giakki/uncss#194]
```ReferenceError: Can't find variable: requestAnimationFrame.```
https://gyazo.com/ee8f7065d572dbb633c19c0eee8a332e

I believe this because phantom doesn't support rAF, but even when I put the polyfill on page, it still throws this error.

**Comment by RyanZim** [comment]
@hellsan631 Is this still an issue?

**Comment by hellsan631** [comment]
Unknown at this time. I tested it on an older stack and it worked, but that stack didn't have a specific implementation of rAF that was known to me. I will see at some later date if this is still a problem when I implement this on my Angular 2 stack (which uses Univeral JS to render on server)

**Comment by RyanZim** [comment]
@hellsan631 ping?

**Comment by hellsan631** [comment]
Just tried it out today, and it looks like this issue is solved :)
