### ISSUE TITLE
Remove CSS used

### ISSUE THREAD

**Issue by LeG3nDz** [giakki/uncss#198]
Hi,

When i lunch my task, the new CSS file has been creat but unCSS has remove more line used :)

The plugin is based on the classes ? URL has all classe removed in the html code.

Example : not see the classe in "wp_nav_menu" (for wordpress)

Thank you !

**Comment by RyanZim** [comment]
If the classes are added on user interaction, they will be removed unless you list them in the `ignore` option. Please close this.

CC: @mikelambert
