### ISSUE TITLE
Getting a list of unused styles, or invert the output?

### ISSUE THREAD

**Issue by EyePulp** [giakki/uncss#200]
Howdy - I was wondering if there was an option to get a list of unused styles, essentially the inverse of what uncss currently creates.  I'm trying to clean out a lot of old styles in our code, and it's pretty tedious to verify each one is **not** coming out in the results from uncss.

Thanks!

**Comment by mikelambert** [comment]
This should do what you want:
uncss(
  [files],
  {
    report: true,
    ...
  },
  function (err, output, report) {
    var all = report['selectors']['all'];
    var used = report['selectors']['used'];
    // var unused = all - used; (using some set subtraction, don't recall how to do this in js offhand)
  }
);

**Comment by EyePulp** [comment]
Great, thanks for the response and the nifty module!

**Comment by dragthor** [comment]
```
var all = report['selectors']['all'];
var used = report['selectors']['used'];
var unused = all.length - used.length;
```

**Comment by RyanZim** [comment]
@mikelambert Any reason to keep this open?

**Comment by atul-bajpai** [comment]
can you please tell me how to run this through grunt
