### ISSUE TITLE
Pass formdata/ login credentials in Uncss

### ISSUE THREAD

**Issue by Ajeetlakhani** [giakki/uncss#204]
I need to access the login controlled area of my website. Using phantomjs i can do  this but i did not get any examples on how to do it in uncss ?

**Comment by a1Gupta** [comment]
@giakki  I am facing the same problem. Any updates on this ?

**Comment by RyanZim** [comment]
To quote @mikelambert in https://github.com/giakki/uncss/issues/176:

> if PhantomJS supports it, then I assume it's just a matter of making an option that plumbs it all the way down to our use of the PhantomJS API If someone wants to do that...but I have no time to design or build such features myself, as they are not relevant for my personal use of uncss.

Please close this.
