### ISSUE TITLE
Pseudo elements `::-webkit-outer-spin-button` and `::-webkit-inner-spin-button` being removed

### ISSUE THREAD

**Issue by jacobbuck** [giakki/uncss#206]

**Comment by XhmikosR** [comment]
@mikelambert: I think this was fixed by your patch in https://github.com/giakki/uncss/pull/211, right?

**Comment by XhmikosR** [comment]
BTW this is duplicate of #199

**Comment by mikelambert** [comment]
Yes, my commit should have fixed this.

**Comment by jacobbuck** [comment]
:+1:
