### ISSUE TITLE
How to access secure resources

### ISSUE THREAD

**Issue by nitinsurana** [giakki/uncss#207]
Googled and went through the readme, couldn't figure out if it's possible to login and maintain session and then access secure pages.

**Comment by RyanZim** [comment]
UnCSS is built only to handle .html files, not server-side files. So at the current time, no. This might be possible if we implemented https://github.com/giakki/uncss/issues/176 or https://github.com/giakki/uncss/issues/186.

**Comment by mikelambert** [comment]
I'm not sure what you mean by "not handle serverside files", as uncss should be able to request web resources as well in its browser. (Though yes, there is no concept of session state as far as I can tell.) As far as passing credentials, yes that is covered by the other bug.

**Comment by RyanZim** [comment]
I meant you can't parse .asp etc. directly.
