### ISSUE TITLE
Option to be less strict for template fragments

### ISSUE THREAD

**Issue by skyl** [giakki/uncss#209]
If I have the css

```
#content .foobar {
	width: 1000px;
}
```

and the html

```
<div class="foobar">OK!</div>
```

I was hoping that the css would be retained instead of removed by uncss. Is there an option to keep the css rule given the html? Would it be very hard to add such an option? I haven't started looking at the uncss code much yet.

**Comment by mikelambert** [comment]
uncss is not designed to be used on template fragments, just complete pages. (For my project, I am planning to render the relevant pages and run uncss against that.)

Template fragments open a big can of worms, such as:
- template fragments may not be parseable html
- template fragments may use template macros to generate class="..."

The existing system actually loads the pages and renders it in a browser (including running any on-load javascript that may add/remove css classes). Template fragments that attempt to be rendered like this can cause their javascript to fail horribly too.

https://github.com/purifycss/purifycss might work better for you, as it appears to do more word-based matching and isn't based on whole-page-rendering-in-a-headless-browser like uncss.
