### ISSUE TITLE
Odd warning with local Ajax call

### ISSUE THREAD

**Issue by HugoGiraudel** [giakki/uncss#213]
When uncss runs on a page that performs a local Ajax call ([like this](https://github.com/bdadam/OptimizedWebfontLoading/blob/master/src/js/fontloader.js#L50-L63)), it emits this warning in the console:

```
NETWORK_ERR: XMLHttpRequest Exception 101: A network error occured in synchronous requests.

  local:25 in loadFont
  local:27
```

I run uncss like this:

```
uncss _site/index.html > _site/css/main.uncss.css
```

I believe it comes from phantomJS having an issue with local Ajax calls, but I might be wrong. Any idea how I could prevent this from happening?

**Comment by RyanZim** [comment]
> I believe it comes from phantomJS having an issue with local Ajax calls

That's what I would guess. No idea how to prevent it. @mikelambert?

**Comment by RyanZim** [comment]
@HugoGiraudel I haven't tried it personally, but you could try using something like https://github.com/tapio/live-server.

Install it globally and run `liveserver _site`. Your browser will open to a localhost address (probably `http://localhost:8080`). Copy the url in the browser bar and run 
`uncss <url> > _site/css/main.uncss.css` in a new terminal window (replacing `<url>` with the localhost url, of course).

If that works, please close this. If not, let me know.

**Comment by RyanZim** [comment]
@HugoGiraudel Have you tried this?

**Comment by HugoGiraudel** [comment]
I did not, and unfortunately I don’t think I’ll have time any time soon. Maybe we could close and re-opn if needed?
