### ISSUE TITLE
gulp-uncss removes class which is added using javascript

### ISSUE THREAD

**Issue by aseem2625** [giakki/uncss#224]
Reasking the question asked at issue #221 as I thought, that question is not clear.

My gulp-uncss configuration is

gulp.task('uncssme', function () {

    return gulp.src('src/css/**/*.css')
        .pipe(uncss({
            html: ['src/**/*.html']
        }))
        .pipe(gulp.dest('dist/css'))
       });
And I am adding a 'newClass' through javascript
         
    document.getElementById('good').className += ' newClass';

But by 'newClass' selector is getting removed from CSS file because it is not used directly in html files.
Please, add a way to add parse js files to rectify this problem.

I am already using,

    /* uncss:ignore */
    .newClass {
      background-color: blue;
    }

But it is bad practice to mention this ignore comment every time I dynamically add a class.
So, please suggest a way to achieve this.

**Comment by mikelambert** [comment]
UnCSS works by rendering the page, which includes running all the associated JS.

If the JS adds the CSS tag, then UnCSS will detect the CSS as being used.

If the JS only runs in response to certain user input or events, then the browser has no way to detect that the CSS code will be used, and will remove it.

No, parsing Javascript code to understand intent is not an option. Consider:
1) if (DEBUG) { addDebugCSSClass(element); }
2) GetClassFromServerUrl(url, function (cssClass) {addCSSClass(cssClass); })
3) fieldname = "className", AppendToField(fieldname, " someClassName");
...etc... This becomes a very hairy and annoying problem very quickly.

Going to close this issue, as the "parse JS" won't be done, and the "track CSS added through JS page load" should already work.
