### ISSUE TITLE
Условие /*! uncss:ignore */ не работает

### ISSUE THREAD

**Issue by Vadizar** [giakki/uncss#226]
Условие /*! uncss:ignore */ не работает в таком примере:

/*! uncss:ignore */
@keyframes warp {
from {
opacity: 0;
transform: rotate(-60deg) translateZ(-300px)
}
to {
opacity: 1;
transform: rotate(60deg) translateZ(300px)
}
}

**Comment by RyanZim** [comment]
Translation:
> Conditions / *! uncss: ignore * / not running in this example:

**Comment by RyanZim** [comment]
You need to put `/* uncss:ignore */` before the class that calls the keyframe.

This example will work:
```
/*! uncss:ignore */
.class {
  animation-name: warp;
}
@keyframes warp {
  from {
    opacity: 0;
    transform: rotate(-60deg) translateZ(-300px)
  }
  to {
    opacity: 1;
    transform: rotate(60deg) translateZ(300px)
  }
}
```
---
Translation/Перевод::

Вам нужно положить `/ * uncss: игнорировать * /` перед классом, который вызывает ключевой кадр.

Этот пример будет работать:
```
/*! uncss:ignore */
.class {
  animation-name: warp;
}
@keyframes warp {
  from {
    opacity: 0;
    transform: rotate(-60deg) translateZ(-300px)
  }
  to {
    opacity: 1;
    transform: rotate(60deg) translateZ(300px)
  }
}
```

Используйте Гугл переводчик

**Comment by Vadizar** [comment]
It does't works.

**Comment by RyanZim** [comment]
@Vadizar Can you paste your _exact_ css?

**Comment by RyanZim** [comment]
@mikelambert It seems this was abandoned by the OP. Can you close this?

**Comment by mikelambert** [comment]
Closing. It's possible the switch to postcss fixes keyframe handling.
