### ISSUE TITLE
Cant figure out command line cli --ignore

### ISSUE THREAD

**Issue by roikles** [giakki/uncss#230]
I'm trying to ignore rules that start with `.grid` in my css using the following:

`uncss http://localhost/e3/**/*.php > unused.css  --ignore '^.grid'`. 

I expected that rules such as `.grid__item` would be ignored but they are still being parsed and removed. I suspect the issue is with my regex but I'm not certain.

If it helps I am runnin the following command from an NPM script:

```
"scripts": {
    "css-remove":"uncss http://localhost/e3/**/*.php > unused.css  --ignore '^.grid'",
    "css-report": "npm run css:removeunused && diff style.css unused.css > diff.css && rm unused.css",
    ...
}
```

I'm using `diff` to generate a third file that contains the difference between `style.css` and `unused.css` so that I can go through and manually clean up any unused rules. The files are all created as expected it's just my regex that seems to fail.

**Comment by mikelambert** [comment]
Try: `--ignore '/^.grid/'` (also if you're doing regexes, you may want `/\.grid/`, as `/^.grid/` will match `agrid`

**Comment by roikles** [comment]
Thanks @mikelambert I will try this out! I know it was down to user error and I really appreciate the help!
