### ISSUE TITLE
How to ignore li.active

### ISSUE THREAD

**Issue by findjonmos** [giakki/uncss#233]
My ignore options look like so, but this class or full selector rule is always removed:
ignore: [
          ".active",
          "li.active",
          "/li.active/",
          "/active/",
        ]

The css for this selector rule looks like so - the .active_class is added on hover so I am not sure how to keep this full selector rule:
nav.bottom ul.categories > li.active_mobile a.categories_main:before,
nav.bottom ul.categories > li.active_mobile a.categories_main:after{}

This is a legacy project that I am trying to clean up

**Comment by RyanZim** [comment]
At the current time I think you have to do:
```
ignore: [
"nav.bottom ul.categories > li.active_mobile a.categories_main:before",
"nav.bottom ul.categories > li.active_mobile a.categories_main:after"
]
```

**Comment by RyanZim** [comment]
Oops, my bad; should be: 
```
ignore: [
"nav.bottom ul.categories > li.active_mobile a.categories_main"
]
```
UnCSS ignores pseudo-selectors.

**Comment by RyanZim** [comment]
@mikelambert Can you close this?
