### ISSUE TITLE
Syntax Error running uncss

### ISSUE THREAD

**Issue by funbunch** [giakki/uncss#234]
I'm trying this for the first time and getting a syntax error saying unexpected token. It looks to be having a problem with the dot '.' in front of pipe(uncss.....). Am I missing any obvious errors here? 

  
    gulp.task('css', function() {
        return gulp.src('stylesheets/*.css')
            .pipe(uncss({
                  html: ['*.html']
             }))
           .pipe(gulp.dest('./out'));
     });

**Comment by mikelambert** [comment]
What is 'uncss' in the above code? I suspect you should be using gulp-uncss and not uncss.

**Comment by funbunch** [comment]
That is simply the name I gave to my task. I will be running multiple tasks not shown above. I could've just used 'default'. 
Suddenly now I'm getting a different error though saying cannot find module gulp.uncss. Even though it's shows installed.
