### ISSUE TITLE
Can't find uncss

### ISSUE THREAD

**Issue by funbunch** [giakki/uncss#235]
I've installed and uninstalled the plugin multiple times using 
     `npm install gulp-uncss --save-dev`

and and keep getting a cannot find module gulp-uncss error. I see it in my node folder and in the package.json.

**Comment by mikelambert** [comment]
This is the issue tracker for uncss, not gulp-uncss. Perhaps you meant to submit this in https://github.com/ben-eb/gulp-uncss ?
