### ISSUE TITLE
Multi-Class Selectors

### ISSUE THREAD

**Issue by RyanZim** [giakki/uncss#237]
If I have this in my html:
```
<p id="one">Hello world! This is a <span class="bug">bug!</span></p>
```
And my JS adds `.used` to the `<p>` on a click event, and my css looks like:
```
.used {
  color: blue;
}
.used .bug {
  background-color: red;
}
```
If I set the `ignore` option to `['.used']`, UnCSS will output:
```
.used {
  color: blue;
}
```
You can test this by downloading [this gist](https://gist.github.com/RyanZim/0ce9084215497ce9ce5a2bedfb87e622) and running `npm i` and `npm run css`.

I need to specify `['.used', '.used .bug']` or `[/\.used.*]` as the `ignore`. This is inconvenient.

For example, bootstrap has a js-inserted class that they use in a variety of components; `.in`. The possible combinations are almost too numerous to write out, and a regex like `/.*\.in/` allows selectors like `.table > thead > tr > td.info`.

Looking over the past issues, it seems different people have reported this; see https://github.com/giakki/uncss/issues/161, #169, and https://github.com/giakki/uncss/issues/184.

Perhaps we could change the handling of the `ignore` option to better accommodate such cases. I would be fine with having the alternate behavior behind a flag.

CC: @XhmikosR & @mikelambert

**Comment by XhmikosR** [comment]
I think this is normal.

The `.used` selector is matched alone. If you want more you should use a regex.

**Comment by RyanZim** [comment]
I know this is the normal behavior, this is a feature request for offering "smarter" matching behind a flag.

I think this would be convenient. Writing a Regex that will match _every_ rule, and no others, is not fun. I'd be willing to do a PR.

**Comment by XhmikosR** [comment]
But it's either a regex or selector. What else could it be?

I'm not sure this makes sense at all. If one understands that ignore is all
regex then it's straight-forward IMO.

**Comment by mikelambert** [comment]
I believe /\.in\b/ should solve the problem with /\.in/ matching too much. So I guess the question is whether using an existing regex feature is better or worse than implementing new matching features. I tend to the err on the side of less features, but I'm also quite familiar with regards, so am possibly biased. :p

**Comment by RyanZim** [comment]
Thanks for the suggestion @mikelambert. The only problem with that Regex is that is will not match `.class.another` or `.class#id`. I modified it to `/.*\.class([\.].*|\b)/` to handle this case. Thanks to you all for your help; I got things working the way I wanted them. Closing.
