### ISSUE TITLE
Separate base styles

### ISSUE THREAD

**Issue by albertvolkman** [giakki/uncss#239]
Is there a method to separate out common the base CSS selectors, and then create separate per-page CSS files so that you get _only_ the CSS required for each page?

**Comment by RyanZim** [comment]
I'm not sure what you're asking. If you pass a single html file to UnCSS, you _will_ get only the CSS required for each page.

**Comment by albertvolkman** [comment]
I'm saying that it'd look at a site as a whole, determine which selectors are common across all pages, save those to something like base.css, and then create a css file for each individual page. Does that make sense?

**Comment by RyanZim** [comment]
I don't know of any way to do that at the present. I'm curious what your use-case for this is (as this adds an extra http request).

**Comment by mikelambert** [comment]
From what I understand: Given a set of CSS files, you want to find the common subset of them, and subtract it out into an additional CSS file.

There's nothing specific to uncss in your feature request, as it's something that can be post-processed by an independent tool, after uncss finishes its work to generate those trimmed CSS files. It also is useful to others even when they are not using uncss (as evidenced by webpack supporting such a feature). As such, I don't believe this should be a feature of uncss.

If you are interested, I believe webpack offers this feature. Just search for CommonsChunkPlugin in these docs:
https://webpack.github.io/docs/stylesheets.html
https://webpack.github.io/docs/code-splitting.html
https://github.com/webpack/docs/wiki/optimization

I'm sure there might be use for a common-factor tool independent of webpack too, that one could hook up to uncss in an external-to-webpack environment, that could then be wired up with more work (more work than webpack's automatic framework, I mean). But I haven't searched too hard out there to see if something like this exists.

**Comment by RyanZim** [comment]
I agree that this should be a separate tool. Someone should write a postcss plugin. :grinning:

**Comment by albertvolkman** [comment]
Thanks 👍
