### ISSUE TITLE
how to move unused css rules to new file in grunt uncss task

### ISSUE THREAD

**Issue by atul-bajpai** [giakki/uncss#253]
Grunt uncss remove the unused css rules. My question is that is there a way by which instead of removing unused css rules, it will put them in a separate file

**Comment by pconerly** [comment]
If you enable `report:true` and use my branch https://github.com/giakki/uncss/pull/256 then you can get a list of unused css selectors.

**Comment by RyanZim** [comment]
#256 has been merged. Is this a satisfactory resolution @atul-bajpai?

**Comment by atul-bajpai** [comment]
yes
