### ISSUE TITLE
HTML parsing stops if a link to a script times out

### ISSUE THREAD

**Issue by maskedcoder** [giakki/uncss#257]
I am using Windows 10 x64, Node v4.2.6, and UnCSS v0.14.1. Basically, what seems to be happening is that UnCSS ignores all elements encountered after a `<script>` tag link (with an absolute URL) that times out.

For example, with my internet service, a link to jQuery on cdnjs takes around 350 milliseconds to load. If the UnCSS `timeout` is set to _any number_ below the actual load time, the parsing stops at that tag. So a file like this:

```html
<html>
  <head>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

    <link rel="stylesheet" type="text/css" href="main.css">
  </head>

  <body>
    <p>Lorem ipsum dolor...</p>
  </body>
</html>
```

Gets treated like this:

```html
<html>
  <head>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
```

All selectors that don't match elements _before_ the `<script>` are removed.

If the `timeout` is set at the right spot, the UnCSS results will change about every time it runs.

The parsing **only** stops if the request times out, so raising the `timeout` in the configuration is a possible workaround. Inline scripts and links to relative URLs are safe, as are tags with `async` and `defer`.

Could you make a timed-out script not stop the parsing?

---

Here's a [repo to demonstrate the issue](https://github.com/maskedcoder/UnCSS-absolute-url-bug). After installing the dependencies, use `gulp` to build the project. The original stylesheet is **/app/main.css**; the generated stylesheet will appear as **/dist/main.css**. I have the timeout set to a very low number, so the problem should show up. If it doesn't, setting `timeout` to 0 might do it.

**Comment by RyanZim** [comment]
I'm not sure. Ping @XhmikosR @mikelambert.

BTW, is there a way to operate without any kind of timeout? I never studied that much since my pages aren't JS-heavy and I don't use CDN links.

@maskedcoder On another point: is there a specific reason for having the script in the head?

**Comment by maskedcoder** [comment]
I originally discovered this when I added TypeKit to a page and the build immediately broke. TypeKit recommends that the embed code be near the top of the `<head>`. It's probably so the font can download sooner, so the FOUT (or FOIT, whatever you pick) shows up less.

Here's an example TypeKit embed code:

```html
<script src="https://use.typekit.net/######.js"></script>
<script>try{Typekit.load({ async: true });}catch(e){}</script>
```

Other than TypeKit, I generally keep scripts at the bottom of the `<body>`.

**Comment by RyanZim** [comment]
@maskedcoder On looking into this further, I don't think this is possible. The code that controls this is: https://github.com/giakki/uncss/blob/master/src/phantom.js#L91-L107.

**Comment by maskedcoder** [comment]
Just to see if I understand correctly, I'll explain it in my own words. All UnCSS does for processing the html is hand it off to PhantomJS, and then uses a custom timeout to stop waiting for PhantomJS. When something takes a while in PhantomJS, the timeout will stop before PhantomJS finishes, and what PhantomJS has done already is all you get. Seems like a really good way to learn about the difference between blocking and non-blocking requests.

I guess for this to be resolved, PhantomJS would have to make a change to their API. For example, they could make an option for disabling links to external scripts or something like that.

**Comment by RyanZim** [comment]
> I guess for this to be resolved, PhantomJS would have to make a change to their API.

Yeah, given the number of issues open there, I don't anticipate such a change getting done anytime soon.

Since this is a PhantomJS issue, this should be closed as out-of-scope.

**Comment by mikelambert** [comment]
This might list some example ways to make this work within uncss:
http://stackoverflow.com/questions/11340038/phantomjs-not-waiting-for-full-page-load/14748934#14748934

ie, checking document.readyState instead of just relying on a timeout.

I was under the impression (after reading the above) that the promise called by phridge's openPage (https://github.com/peerigon/phridge#user-content-working-in-a-page-context, which internally calls http://phantomjs.org/api/webpage/method/open.html) was called after the page loads (but before any asynchronous loads), but I guess I'm mistaken on all that. But perhaps the above approach might work for someone motivated to apply it to uncss.
