### ISSUE TITLE
RFE: Strip unused @font-face statements

### ISSUE THREAD

**Issue by Herst** [giakki/uncss#258]
It would be great if unused `@font-face` rules could also be stripped.

A classical example would be a page using Bootstrap 3 but none of the shipped Glyphicons font icons. The classes for the Glyphicons symbols get stripped, so the Glyphicons font becomes unusable, but `uncss` still leaves the corresponding `@font-face` declarations in there.

**Comment by RyanZim** [comment]
@Herst This is out of scope IMO, use cssnano or similar.

CC: @mikelambert

**Comment by RyanZim** [comment]
@mikelambert @XhmikosR Should this be closed or is this something you would consider adding?

**Comment by mikelambert** [comment]
The font is still usable, because it can be referenced from a style property directly. Uncss checks all element classes to determine usability, but doesn't look at style properties, because they're normally irrelevant for determining what *.css content can be deleted.

**Comment by Herst** [comment]
In my case the `font-face`s became `url(data:base64)` if remember correctly (could be because I deleted the font files).

**Comment by RyanZim** [comment]
@Herst That is due to something else in your toolchain, not uncss. Add cssnano to your toolchain to remove the `font-face`s.

**Comment by RyanZim** [comment]
@mikelambert Any reason to keep this open?

**Comment by RyanZim** [comment]
@mikelambert ping?
