### ISSUE TITLE
am alwasy getting "'C:\Program' is not recognized as an internal or external command, operable program or batch file." error

### ISSUE THREAD

**Issue by rajsek** [giakki/uncss#261]
when it try to run below code am always getting below error 
`var uncss = require('uncss');

var files   = ['index.html'],
    options = {
        csspath      : 'css',
        timeout      : 1000,
        report       : false,
    };

uncss(files, options, function (error, output) {
    console.log(output);
});
`
Error 

F:\Mani Code\temp\Dev_EpicHospitality>node uncss.js
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
undefined

**Comment by RyanZim** [comment]
@rajsek how are you running the code above?

**Comment by RyanZim** [comment]
@rajsek Has this been resolved?

**Comment by RyanZim** [comment]
@mikelambert This looks abandoned, can you close?
