### ISSUE TITLE
uncss use first file for all other

### ISSUE THREAD

**Issue by thomas2411** [giakki/uncss#262]
I use grunt-uncss which is configured like this:

        uncss: {
            options: {
                ignoreSheets: [/fonts.googleapis/]
            },
            dist: {
                files: [
                    {
                        dest: 'dist/css/site1.css', src: ['src/site1.html']
                    },
                    {
                        dest: 'dist/css/site2.css', src: ['site2.html']
                    },
                    {
                        dest: 'dist/css/site3.css', src: ['site3.html']
                    }
                ]
            }
        },

In site1.html, site2.hml, site3.html I have linked the same CSS files from assets dir and one files which is distinct for each of these pages, like this:

    
    <link rel="stylesheet" href="assets/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/app.css">
    <link rel="stylesheet" href="assets/css/blocks.css">
    <link rel="stylesheet" href="assets/css/one.style.css">
    <link rel="stylesheet" href="assets/css/footers/footer-v7.css">
    <link rel="stylesheet" href="assets/plugins/font-awesome/css/font-awesome.css">
    <link rel="stylesheet" href="assets/css/app.style.css">
    <link rel="stylesheet" href="assets/css/custom.css">
    <link rel="stylesheet" href="site1/styl.css">
    

It worked OK but I don't know why it stopped. Now for each sites it takes styl.css file from the first in the configuration, which is site1. 
So in the end each site has style.css from site1
I use MAC OS X Sierra (recently updated). My package.json looks like this:

```
{
  "name": "myname",
  "version": "1.0.0",
  "description": "BlaBla",
  "license": "private",
  "devDependencies": {
    "grunt": "v1.0.0",
    "grunt-contrib-copy": "^1.0.0",
    "grunt-contrib-cssmin": "^1.0.1",
    "grunt-contrib-htmlmin": "^2.0.0",
    "grunt-processhtml": "^0.4.0",
    "grunt-uncss": "^0.6.1"
  }
}
```

**Comment by RyanZim** [comment]
Not sure what the issue is here, I don't use grunt. @addyosmani @XhmikosR?

**Comment by romanlelek** [comment]
Hello, I have similar issue - connected with Sierra update - before the update my settings worked perfectly, no problem, after update the same configuration stopped working anymore. But strange thing is that I cant see any error - when I run uncss task, it says Finished, but nothing is created in dist folder as before - the task doesnt create any output file.

My settings:

`module.exports = function(grunt) {
    return {
        dist: {
            files: [
                { src: '<%= paths.dist %>/all_transactional.html', dest: '<%= paths.dist %>/css/nomediaq.css' }
            ]
        },
        options: {
            compress: true,
            ignore: ['.ExternalClass', '.ExternalClass p', '.ExternalClass span', '.ExternalClass font', '.ExternalClass td', '.ExternalClass div', 'a[href^=tel]',
                'a[href^=sms]', 'a[x-apple-data-detectors]', 'a:hover', 'code', 'pre', '.btn_hoover', '.menuContent a', '.yshortcuts', '.ReadMsgBody'
            ]
        }
    }
}`

Anyone any idea what should I change? Thank you.

Best regards,
Roman

**Comment by RyanZim** [comment]
@thomas2411 @romanlelek It would probably be best to try opening an issue at https://github.com/addyosmani/grunt-uncss/issues.
