### ISSUE TITLE
execute uncss with a javascript file

### ISSUE THREAD

**Issue by crico** [giakki/uncss#263]
Is it possible to execute uncss against a javascript file? such that: 
`uncss libs/myscript.js media/css/mycss.css > output.css`

I am trying it but output.css doesn't contain the css rules used by javascript file. For example, adding a class with js:
`$(element).addClass('form-field-error');`

I have a validation javascript that includes error styles when the data is wrong. I am trying to execute uncss against an array of different types of files: smarty templates (tpl), javscripts, ...

**Comment by RyanZim** [comment]
@crico That isn't possible, uncss actually runs your files as html in a headless web browser. Some types of template files might work if the template is valid html, but raw javascript will not work.

Currently, the best solution for including error styles is to use the `ignore` option.

Note that uncss will parse classes/selectors added by the javascript during the page load (when you run uncss on the html file), but not those dynamically added by user interaction.
