### ISSUE TITLE
checking html from server recursively

### ISSUE THREAD

**Issue by baomastr** [giakki/uncss#264]
How can i check files on server if i need to clean up my styles and want uncss to check my site with all subpages

the next string doesn't match. it checkes only main page

> .pipe(uncss({
            html: ['http://mysite.com/', 'http://mysite.com/**', 'http://mysite.com/**/**', 'http://mysite.com/**/**/**/']
}))

**Comment by RyanZim** [comment]
@baomastr Globbing only works on local files, not on remote URLs. If you can't test against local files, you will have to pass each URL individually to uncss. If your site is large and you have a sitemap, it may be worth writing a script to get the list of URLs from the sitemap.

If this answers your question, please close this. Thanks!

**Comment by baomastr** [comment]
Thanks for answer

**Comment by CaptainQuirk** [comment]
> If your site is large and you have a sitemap

In this situation, it's likely that all those pages will **share** the same css file(s). 

If **uncss** is launched individually on all urls gathered in the sitemap, it is likely that the analysis of **page A** will report styles that are actually not used on **page A** but are on **page B**.

Would one have to gather all the reports and filter them ?

**Comment by RyanZim** [comment]
@CaptainQuirk Not entirely sure what you're asking.

If you have multiple pages that use the same CSS, and you would like to keep it that way, you can pass multiple HTML files to one run of `uncss`. This will produce the CSS that is used by any of the pages, but with totally unused styles removed.
