### ISSUE TITLE
Consider jsdom

### ISSUE THREAD

**Issue by RyanZim** [giakki/uncss#265]
Given the number of PhantomJS-related issues we've had in the past, as well as the ongoing #250, perhaps this is worth looking into.

https://github.com/tmpvar/jsdom is:

> A JavaScript implementation of the WHATWG DOM and HTML standards, for use with node.js

The goal is to make something similar to a headless browser in pure node.js, without any external binaries (we all know how slow PhantomJS installs). It doesn't actually graphically render the page, but uncss doesn't need that.

A comparison to PhantomJS: https://github.com/tmpvar/jsdom#jsdom-vs-phantomjs.

There is a slight security concern, the jsdom sandboxed psudo-browser instance is not foolproof; if you try hard enough, you can get to the node.js environment and your machine. (https://github.com/tmpvar/jsdom#on-running-scripts-and-being-safe) Since uncss primarily is running your own trusted code, I think a bold warning on the uncss README warning you not to try running uncss on untrusted webpages would be sufficient.

Uncss primarily uses `document.querySelector()`; that pattern matching is provided by https://github.com/dperini/nwmatcher. Here is the list of supported selectors: https://github.com/dperini/nwmatcher/wiki/CSS-supported-selectors (Pretty Good!).

I would be interested to know what the community's thoughts are on this.

I don't know if/when I'd get time to attempt to port uncss from PhantomJS to jsdom; if I had time, I'd be glad to try.

Attn: @giakki @XhmikosR @mikelambert @saalmaan @lorvent

**Comment by lorvent** [comment]
phantomjs is causing some problems for sure and if jsdom can solve those problems and having all features of phantomjs....it would be great to replace with jsdom

**Comment by vseventer** [comment]
I ran into issues with PhantomJS as well, and have taken the liberty to port things over to jsdom (see [`jsdom` branch](https://github.com/vseventer/uncss/tree/jsdom)). There are some minor issues I still need to figure out, and I'm sure code can be improved, but at least things are working.

@RyanZim @lorvent If you fancy, you can try using the jsdom branch, and see if that fixes things for you.

**Comment by lorvent** [comment]
Sure, i will check and let you know

**Comment by RyanZim** [comment]
@vseventer Haven't tried it, but LGTM on the surface. Thanks for doing this; I just don't get time.

**Comment by RyanZim** [comment]
@vseventer I just tried out your branch, it works great! I did a little cleanup and submitted a PR to your fork https://github.com/vseventer/uncss/pull/1.

I never had any actual issues with PhantomJS, other than the fact that it was slow, so I can't say if it actually fixes all the PhantomJS issues. @lorvent Have you tried this yet?

@giakki @XhmikosR @mikelambert I'm very much in favor of merging @vseventer's fork in here; thoughts? @vseventer Looking forward to a PR here.

**Comment by vseventer** [comment]
@RyanZim Thanks - looks good. The resemble tests are currently not working, have to look into that, not sure what the point of them is anyway.

Regarding the switch to jsdom, I was running into #250, stumbled upon this ticket, and figured it was worth the try. For me, it solved the issues I was having, and the resulting CSS file is identical as when using PhantomJS.

The only gotcha is the way jsdom executes JavaScript (it uses Node.js vm), outlined [here](https://60devs.com/executing-js-code-with-nodes-vm-module.html#performance). I therefore [changed](https://github.com/vseventer/uncss/commit/dd2113f5866cad572c752976b9c658b4ace17e67#diff-a5bf5a7430099f9576d18ad3aaa4b0a8) the test in `tests/jsdom/long_wait.html`, otherwise it wouldn't terminate (or at least, I didn't have the patience to wait more than a few minutes).

**Comment by RyanZim** [comment]
@vseventer Resemble tests work fine for me, not sure why they don't work for you.

Wasn't sure why you edited that test, thanks for explaining. In either case, I think we should release this as a breaking change since there is bound to be a few edge cases that are different from PhantomJS. The next release is planned to be breaking anyhow, due to dropping support for earlier versions of Node.

**Comment by RyanZim** [comment]
@vseventer Regarding resemble tests not working for you, have you tried running `rm -rf node_modules && npm i` on your `jsdom` branch?

What's your OS & Node version?

I'm running Lubuntu (an Ubuntu Linux derivative) and using Node v7.

**Comment by vseventer** [comment]
I'm using OSX with Node 4, but also tried with Node 6 and 7. Seems to be a problem with PhantomJS (segmentation fault). Since the tests are passing for you, must be a local issue, so should not be a blocker for this to move into master, if interested.

**Comment by RyanZim** [comment]
@vseventer I don't have write access here, but please do open a PR for this. Thanks!

**Comment by kapouer** [comment]
Am going to test this on a real world project tonight ! so happy !

**Comment by mikelambert** [comment]
FWIW (as the person approving most commits these days), I think I would be happy with switching to jsdom over PhantomJS. PhantomJS has a strange API to work with, and has often been flaky as a result of the underlying implementation.

However, I am worried about it not actually being a 'real browser' from what I can tell (unlike PhantomJS's headless webkit), and what compatibility issues we might run into as a result: JS that uses feature-detection, checks browser user-agents, running at startup in response to browser onload events, etc. It just feels like a bigger unknown. So upping the major version number obviously makes sense.

But I'd also like to see a few projects try this out and report success (or at least give us an idea of what kind of migration guide or "known gotchas" we need to list), before I commit to merging it upstream. Though I'm happy to defer to another committer, if they feel more strongly about it and wants to be on the hook for dealing with any fallout. :)

**Comment by RyanZim** [comment]
@mikelambert I appreciate your input on this.

> However, I am worried about it not actually being a 'real browser' from what I can tell (unlike PhantomJS's headless webkit), and what compatibility issues we might run into as a result

I'm a bit worried about that too; from what I understand, jsdom is trying hard to act like a real browser; if any issues are encountered, I think jsdom would try to fix them. IIRC, PhantomJS has some edge cases where it doesn't quite act like a normal browser.

> So upping the major version number obviously makes sense.

:+1: 

---

> But I'd also like to see a few projects try this out and report success (or at least give us an idea of what kind of migration guide or "known gotchas" we need to list), before I commit to merging it upstream.

Not a bad idea; FYI, my pages aren't js-heavy and I don't use any weird feature-detection stuff, so my usage of jsdom probably won't find any edge cases.

I only wish that there was a good way to install the jsdom branch via npm. Perhaps you could merge the changes onto a `jsdom` branch in the main repo and publish a pre-release to npm (keeping the `latest` dist-tag set to the current version)? That way, we could do `npm install -D uncss@1.0.0-beta.1` (or similar) to try the new version.

I assume you saw @vseventer's comment about slow global lookups in jsdom. That would be one known gotcha. I would venture to suggest that a fair amount of uncss users wrap their JS in an IIFE or use a module bundler; in which case this gotcha doesn't "get'em."

**Comment by mikelambert** [comment]
I believe anyone who wants to test should be able to run "npm install https://github.com/vseventer/uncss#jsdom" to test it in their project.

**Comment by vseventer** [comment]
Agreed more real-life testing would be welcome.

Personally, I'm using uncss for my blog, which uses Leaflet (classes added dynamically), Bootstrap and thus also jQuery (minimal custom build), bundled with webpack. I'm not running into any issues, in fact, everything works fantastic and as expected.

But yeah, jsdom definitely has some shortcomings - I think the known ones are best summarized in its ["html living standard" issues](https://github.com/tmpvar/jsdom/labels/html%20living%20standard).

**Comment by RyanZim** [comment]
@mikelambert Yeah, that's what I've been doing, however, if @vseventer deletes the branch or the fork after changes are merged here, won't `npm install` break for those projects?

**Comment by kapouer** [comment]
I'm in a case where only generated web pages can be inspected, so i suppose it'd be best to crawl my website and feed uncss with that. Or maybe uncss could do that.

**Comment by RyanZim** [comment]
@kapouer You'll need to feed uncss with a list of URLs. Let me know how it goes!

**Comment by mikelambert** [comment]
Yes, if he deletes his branch, then npm install will break on those projects. I was assuming that those people on this thread who are proactive and involved and testing, would also be the type to point at the new uncss version when it's merged in. I think many projects do this (I have numerous private fork references in my package.json)

If you want something that lasts and doesn't break, I would suggest an 'uncss-test' or 'uncss-jsdom' npm module that contains the fork, entirely independent of uncss. And then never delete the module.

**Comment by sparanoid** [comment]
@vseventer I tried the jsdom branch it's extremely fast, here's a simple benchmark tested along with [grunt-uncss-inline](https://github.com/sparanoid/grunt-uncss-inline):

jsdom:

```
...
loading grunt-uncss-inline  705ms  ▇▇▇▇▇▇▇▇ 5%
uncss_inline:dist            2.6s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 17%
concurrent:dist              1.9s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 12%
Total 15.4s
```
PhantomJS:

```
...
jekyll:dist            7.8s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 8%
uncss_inline:dist  1m 19.5s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 87%
concurrent:dist        1.7s  ▇▇▇▇ 2%
Total 1m 31.7s
```

The only downside to me is some CSS syntax cannot be parsed like `@supports`.

**Comment by RyanZim** [comment]
@sparanoid Thanks for the benchmark; I knew it would be fast, but I never tested just how fast.

> The only downside to me is some CSS syntax cannot be parsed like `@supports`.

I wasn't aware of that. Mind opening a separate issue for that?

**Comment by RyanZim** [comment]
@mikelambert @vseventer Test package: https://www.npmjs.com/package/uncss-jsdom. Source code: https://github.com/RyanZim/uncss/tree/uncss-jsdom.

**Comment by vseventer** [comment]
Thanks, very useful. I've not encountered any major issues myself (other than the `long_wait` test I had to change).

@sparanoid I tried running some tests with `@supports`, and everything seems to be working fine. Looking at the uncss source, it appears any conditions starting with `@` are kept, and the group rules inside its body are still uncss-ed.

**Comment by sparanoid** [comment]
@vseventer @RyanZim sorry about that inaccurate information, I found it's not related jsdom but `grunt-uncss-inline` plugin after some tests, so far so good with jsdom.

**Comment by ArmorDarks** [comment]
Wow, glad to see some movement from phantomjs to jsdom. We're having a lot of issues with phantomjs and large codebase too, it just crashes.

So, it seems that jsdom branch can be used relatively safe on production for now?

**Comment by RyanZim** [comment]
> So, it seems that jsdom branch can be used relatively safe on production for now?

I believe so!

**Comment by mikelambert** [comment]
We now use JSDom!
