### ISSUE TITLE
Incorrect output

### ISSUE THREAD

**Issue by Ferym26** [giakki/uncss#266]
Hi, i have a problem with uncss
[repo](https://github.com/Ferym26/CssClean)
Its simple task for clearning, but the output file (out/style.clean.css) has only comments from original style.css 
[trabl](http://joxi.ru/brRelWRuoV6RA1)

**Comment by RyanZim** [comment]
@Ferym26 You are using gulp-uncss-sp; try using https://github.com/ben-eb/gulp-uncss and see if that fixes your problem. If so, please close.

**Comment by Ferym26** [comment]
`.pipe(uncssp({` or `.pipe(uncss({`
never mind. it doesnt work

**Comment by RyanZim** [comment]
I'll try to take a look at this when I get time.

**Comment by RyanZim** [comment]
@Ferym26 Found the problem!

The script http://cdn3.adcombo.org/content/!common_files/js/jquery.min.js takes too long to load and uncss times out. You will need to set a timeout, like this:

```
.pipe(uncss({
  html: ['html/index.html'],
  timeout: 200
}))
```

200 was long enough for me, it may vary depending on the machine.

**Comment by Ferym26** [comment]
it's great. Thank you!
