### ISSUE TITLE
Ignore [type] selectors

### ISSUE THREAD

**Issue by aitormendez** [giakki/uncss#271]
What is the proper syntax to ignore this in the ignore list?:

`.comment-form input[type=email]`

I'm using gulp-uncss. Ignore list could look like:

```
ignore: [
        `/\.comment\-form\ input\[type\=email\]`,
}
```

I tried a lot of options unsuccesfully. Thanks!

**Comment by RyanZim** [comment]
Try this:
```
ignore: [
        /\.comment-form input\[type=email\]/,
]
```
If this works for you, please close this issue. Thanks!

**Comment by aitormendez** [comment]
yes, thanks!
