### ISSUE TITLE
Remove inlined css from external css files

### ISSUE THREAD

**Issue by josenobile** [giakki/uncss#272]
I use [critical](https://github.com/addyosmani/critical) to inline the critical css. How can I instruct to remove from the external css files the inlined css? in addition to the unused css in the css files?

**Comment by mikelambert** [comment]
Sorry, that's out of scope for this project. This project removes unused css. It does not remove used-but-already-listed-in-a-different-file css.

You may be interested in looking at postcss to do what you want: manipulating a css file. It's what uncss uses internally.
