### ISSUE TITLE
bootstrap dropdown menus do not trigger after uncss of bootstrap

### ISSUE THREAD

**Issue by jogaco** [giakki/uncss#274]
Trying to apply uncss to bootstrap.
After applying it to a basic bootstrap example, dropdown menus do not toggle when clicking on the options.

For example, try against: http://www.bootply.com/idWWJSmrKD

**Comment by RyanZim** [comment]
https://github.com/giakki/uncss/wiki/Using-uncss-with-Bootstrap

**Comment by jogaco** [comment]
:thumbsup:

**Comment by RyanZim** [comment]
Glad that helped, sorry for the short reply, I was in a hurry.
