### ISSUE TITLE
Ignore error

### ISSUE THREAD

**Issue by crisdany6** [giakki/uncss#275]
When running using gulp, i am getting following error
`CssSyntaxError: uncss/node_modules/css: unable to parse undefined:
<css input>:130:17: Unknown word
	125:            font: 11px / 140% verdana;
	126:            background: #888800;
`

is there an option to skip errors?

any help would be great,
thanks.

**Comment by RyanZim** [comment]
@crisdany6 You can't skip errors, a syntax error is a syntax error, and that will stop CSS parsing. You will need to fix your CSS syntax error anyhow.

**Comment by RyanZim** [comment]
@mikelambert Can you close?
