### ISSUE TITLE
Ignore regex

### ISSUE THREAD

**Issue by ix-xerri** [giakki/uncss#278]
Hi am trying to create a regex that ignore every selector containing a string.

`ignore: ["/.*me.*/"]` so the css file would contain anything with 'me' such as `.me` and the line `.header .me`

Is that correct? I'm using gulp-uncss.

**[Solved]**

using `new RegExp(".*\.me.*")`

**Comment by RyanZim** [comment]
@ix-xerri You don't need to use `new RegExp`, just do `ignore: [/.*me.*/]`. If you have your problem solved, please close this issue.

**Comment by ix-xerri** [comment]
I tried that but it didn't work. I'll try again tomorrow and will comment if it works. Closing this issue now. Thanks

**Comment by ix-xerri** [comment]
It worked
