### ISSUE TITLE
Using AngularUI

### ISSUE THREAD

**Issue by ix-xerri** [giakki/uncss#279]
I'm trying to use it on a big Angular project which uses [AngularUI](https://angular-ui.github.io/bootstrap/) but some classes are generated at run time. Do I have to exclude all the classes that are used in the project?

**Comment by RyanZim** [comment]
Any class that is dynamically added by JS after the page load (like when a user clicks a button) needs to be manually ignored.

**Comment by RyanZim** [comment]
@ix-xerri @mikelambert Can one of you close this?
