### ISSUE TITLE
HTTPS invalid certificate

### ISSUE THREAD

**Issue by MathRobin** [giakki/uncss#28]
Hi !

How to go around an invalid certificate ? I want to run uncss on a local domain with a non-trusted certificate, uncss says nothing and I know that there are a lot of unneeded css...

Thanks for your tool :)

**Comment by RyoIkarashi** [comment]
I ran `uncss https://sample.dev > /path/to/stylesheet.css` to remove unused styles from my local server with HTTPS and self signed certificates.
but I got an TLS-related error.

Node version: v9.4.0

```
UnhandledPromiseRejectionWarning: Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1041:34)
    at TLSSocket.emit (events.js:160:13)
    at TLSSocket._finishInit (_tls_wrap.js:638:8)
(node:34329) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:34329) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I think self-signed certification options should be provided or ignoring TLS related errors should be applied with something like these options in [`src/utility.js` at Line 112-113](https://github.com/giakki/uncss/blob/master/src/utility.js#L112-L113).

```
request({
  url: filename,
  headers: { 'User-Agent': 'UnCSS' },
  // ignore TLS related errors
  rejectUnauthorized: false,
  strictSSL: false,
  // OR just specify self-signed cert and key
  agentOptions: {
    cert: fs.readFileSync("/path/to/cert.crt")
    key: fs.readFileSync("/path/to/key.key")
  }
}, callback);
```

@giakki What do you think about this?

**Comment by RyanZim** [comment]
@RyoIkarashi Please open a new issue instead of bumping old threads.
