### ISSUE TITLE
Resulting CSS only has html, body and font-face 

### ISSUE THREAD

**Issue by gkatsanos** [giakki/uncss#281]
Just added this:

```
gulp.task('sass', function () {
  let files = `${config.sass.src}/**/*.scss`
  let dest = `${config.sass.dest}`

  console.log('=== Compiling SASS ===')

  return gulp.src(files)
    .pipe(sourcemaps.init())
    .pipe(sass({
      outputStyle: 'expanded',
      precision: 10,
      errLogToConsole: true,
      includePaths: config.bootstrap.src
    }).on('error', sass.logError))
    .pipe(autoprefixer({
      browsers: ['last 6 versions', 'iOS >= 8.1']
    }))
    .pipe(uncss({
      html: 'http://localhost:8888/'
    }))
    .pipe(sourcemaps.write())
    .pipe(gulp.dest(dest))
    //.pipe(browserSync.stream({once: true}))
})
```

http://localhost:8888/ is a PHP (MAMP) generated url (WordPress) which works fine locally.

The resulting CSS only has the html, body and font-face selectors.. 

Cache? PhantomJS isn't finding the page? how to debug?

**Comment by RyanZim** [comment]
Does your HTML contain any external `<script>` tags in the head? If so, that could be the problem. See https://github.com/giakki/uncss/issues/257. Try setting the `timeout` option to a crazy high value, and see if that works.

Another thing, open the page in your browser and make sure there are no errors in the browser console (broken HTML) that could be causing problems.

**Comment by RyanZim** [comment]
If you're feeling adventurous, you could also try the experimental package: https://www.npmjs.com/package/uncss-jsdom. This package uses jsdom instead of PhantomJS and may solve some of these issues.

**Comment by gkatsanos** [comment]
@RyanZim unfortunately it's not the script tags. I hard-removed all scripts, just to be sure (I was loading jQuery from a CDN with defer set - but on the bottom of the page)
I also added A LOT of timeout:

```
gulp.task('sass', function () {
  let files = `${config.sass.src}/**/*.scss`
  let dest = `${config.sass.dest}`

  console.log('=== Compiling SASS ===')

  return gulp.src(files)
    .pipe(sourcemaps.init())
    .pipe(sass({
      outputStyle: 'expanded',
      precision: 10,
      errLogToConsole: true,
      includePaths: config.bootstrap.src
    }).on('error', sass.logError))
    .pipe(autoprefixer({
      browsers: ['last 6 versions', 'iOS >= 8.1']
    }))
    .pipe(uncss({
      html: 'http://localhost:8888/',
      timeout: 9000
    }))
    .pipe(sourcemaps.write())
    .pipe(gulp.dest(dest))
    .pipe(browserSync.stream({once: true}))
})
```

**Comment by gkatsanos** [comment]
**update** seems that command line uncss
`16:21 $ uncss http://localhost:8888 > AAAAA.css`
produces correct results

**Comment by RyanZim** [comment]
@gkatsanos Try `timeout: 90000`, or try the uncss-jsdom package. The jsdom package might at least give you an error message.

**Comment by gkatsanos** [comment]
@RyanZim 90000 didn't work, I'll try `jsdom` - Didn't really see any info on how to set it up though..

**Comment by gkatsanos** [comment]
@RyanZim I changed the gulp-uncss require to be uncss-jsdom, and it worked. Damn. I lost like 2h looking into this.

**Comment by RyanZim** [comment]
@gkatsanos Yeah, didn't think about the fact that you were using gulp-uncss. Glad to hear jsdom works for you.

**Comment by gkatsanos** [comment]
@RyanZim I'm very curious as to why PhantomJS isn't.. any clue?

**Comment by RyanZim** [comment]
All I can say is PhantomJS is: _weird_.

See https://github.com/giakki/uncss/issues/250, https://github.com/giakki/uncss/issues/220, & https://github.com/giakki/uncss/issues/232 for more weirdness.

Guess there's not much more we can do until @mikelambert is ready to merge jsdom; should we close this?
