### ISSUE TITLE
how can you make sure the class which is dynamically added in js will be include after uncss

### ISSUE THREAD

**Issue by rowthan** [giakki/uncss#282]
there are a lot of css was used by javascript as follow：
style.css 
`a{color:red}`  
index.html
`<div class ="b"></div><div id="dynamically"></div>`  
index.js  
`docuMent.getElementById("dynamically").setAttribute("class", "a"); `
or
`$("#dynamically").addClass("a")`

----
after uncss the class "a" will be lost.
so is there any solution？

**Comment by RyanZim** [comment]
@rowthan Either use the `ignore` option, or add an `uncss:ignore` comment to your css:

```css
/* uncss:ignore */
.a {
    /* ... */
}
```

Please close this. Thanks!

**Comment by rowthan** [comment]
all right. that's a way. But actually, the style.css have been made very long ago.
now why i use uncss is to solve the problem that the css is disordered.
i want there is a option that the uncss could analysis the js file which class have been used.
if you are not consider this, maybe i would try to do it.
thanks anyway.

**Comment by RyanZim** [comment]
@rowthan That is out of scope for the uncss project. It does recognize classes added by the JS on page load, but not the ones added by user interaction. https://github.com/purifycss/purifycss can process JS, but it doesn't catch all the unused classes.

**Comment by rowthan** [comment]
thank you very much, that's the very one I want.
please close this issue.
