### ISSUE TITLE
Double Slash Comments Break UnCSS

### ISSUE THREAD

**Issue by depiction** [giakki/uncss#283]
My CSS code has lots of double line comments and UnCSS breaks when it sees them.

    .sidebar,
    .page-navigation,
    .wp-prev-next,
    .respond-form,
    nav {
    	display: none;
    }
} // End of media query

uncss/node_modules/css: unable to parse undefined:
<css input>:83:3: Unknown word
	78:            .respond-form,
	79:            nav {
	80:            	display: none;
	81:            }
	82:            
	83:     -> } // End of media query
	84:

**Comment by RyanZim** [comment]
@depiction Double Slash comments are not valid CSS. Valid CSS requires `/* ... */` style comments.

Please close this issue. Thanks!

**Comment by depiction** [comment]
Per the SASS documentation (http://www.sass-lang.com/documentation/file.SASS_REFERENCE.html#comments), Sass supports standard multiline CSS comments with /* */, as well as single-line comments with //. The multiline comments are preserved in the CSS output where possible, while the single-line comments are removed.

There are use cases for both versions of comments and both are supported by SASS, therefore I think UnCSS should support both.

**Comment by RyanZim** [comment]
@depiction Supporting them would require adding a custom parser as a dependency which would add install size to an already large package. I'm not in favor of it, but I'll leave the final decision to @mikelambert or @XhmikosR.

**Comment by mikelambert** [comment]
So SASS supports single-line comments, but removes them on export because they are not part of the CSS standard.

UnCSS is a CSS parser, not a SASS parser, so I am confused why you think UnCSS should support these? Why don't you throw a SASS parser in front of your UnCSS usage, as a means to fix your comments, since it looks like you prefer SASS syntax?
