### ISSUE TITLE
Keyframes removed if not specified as first value of an animation

### ISSUE THREAD

**Issue by andrew-dixon** [giakki/uncss#284]
The keyframes element is removed if not specified as the first value of an animation, for example:

`animation: 1s bounce 2s;`

where "bounce" is the keyframes name and is syntactically valid, but UnCSS removes the `@keyframes bounce` from the CSS file. However when specified as:

`animation: bounce 1s 2s;`

Which is also syntactically valid, it doesn't remove the keyframes.

**Comment by mikelambert** [comment]
I suspect it's a bug in the following line's use of `[0]`. Care to suggest a pull request to fix it? (I suspect you know more about valid `animation:` syntax than I do)

**Comment by andrew-dixon** [comment]
@mikelambert Problem is, from the documentation (https://www.w3.org/TR/css3-animations/#animation-shorthand-property), I don't believe that the name has to be in any particular position, the only two values that **have** to be in a particular order are the time references as the first is taken to be the `animation-duration` and the second the `animation-delay`. 

You would need to parse the whole string and look for the item in the string that isn't a time definition or a valid value of `animation-iteration-count`, `animation-direction`, `animation-play-state` or `animation-fill-mode`.

I'll have a think about it and see if I can come  up with something.

**Comment by RyanZim** [comment]
I have a patch for this ready, will probably open PR against `develop` after https://github.com/giakki/uncss/pull/335.

**Comment by RyanZim** [comment]
Will be fixed in the upcoming release.
