### ISSUE TITLE
HTML Root not getting passed in when reading stylesheet locations

### ISSUE THREAD

**Issue by marklegault** [giakki/uncss#286]
htmlroot option seems to get dropped from the options when running through uncss, resulting in "could not open..." so all files are still relative to the HTML file, though that might not be the desired behaviour

**Comment by marklegault** [comment]
Dug a bit more. Seems to be an issue with trying to build this locally, in utility.parsPaths where PhantomJS is not showing the files with the file: prefix, so it's never getting the chance to hit the if statement for options.htmlroot

console.log(sheet)
        /* Path already parsed by PhantomJS */
        if (sheet.substr(0, 5) === 'file:') {
            sheet = url.parse(sheet).path.replace('%20', ' ');
            /* If on windows, remove first '/' */
            sheet = isWindows() ? sheet.substring(1) : sheet;

            if (options.htmlroot) {
                console.log("found it")
                return path.join(options.htmlroot, sheet);
            }
            sheet = path.relative(path.join(path.dirname(source)), sheet);
        }

resulted in assets/css/style.css for me. Sorry if I'm doing this wrong, first time trying to dive into someone else's code in grunt

**Comment by RyanZim** [comment]
@marklegault Do the link tags in your HTML have absolute paths?

Example:

    <link rel="stylesheet" href="/assets/css/style.css" />

(Note the leading slash in the URL)

**Comment by marklegault** [comment]
Yes they do.

**Comment by marklegault** [comment]
Using this as part of a Grunt-Jekyll build, trying to incorporate grunt-uncss, so this may be strictly a "me" problem, but it seems like htmlroot should be called checked for before checking whether it's a url or file.

**Comment by marklegault** [comment]
So as a test I went in and moved the options.htmlroot if statement out of the file:// check, and it had the added benefit of stopping the "cannot find variable $" error that it was also throwing..

**Comment by RyanZim** [comment]
@marklegault So is this issue fixed?

**Comment by XhmikosR** [comment]
From my tests, yes. As long as the htmlroot option is passed, v0.15.0 works without errors.

**Comment by RyanZim** [comment]
OK, thanks @XhmikosR. Closing; will reopen if I hear otherwise.
