### ISSUE TITLE
Ruby RSpec/Capybara support?

### ISSUE THREAD

**Issue by G0dwin** [giakki/uncss#288]
I'd like to get uncss support within my Ruby UI tests. Is there any documentation on how to install for Capybara/Poltergeist tests?

**Comment by RyanZim** [comment]
@G0dwin I don't have any experience with Ruby, but I'd be glad to try and answer any specific questions you may have.

I don't know of any docs dedicated to the subject.

**Comment by G0dwin** [comment]
Thanks @RyanZim, I ended up writing my own Ruby Gem to calculate CSS code coverage: https://github.com/lingua-franca/marmara. I may come back to USS at some point to see if we can leverage some common code.

**Comment by RyanZim** [comment]
SGTM, do you mind closing?
