### ISSUE TITLE
when execute gulp on Mac, it show an error. Bad argument 

### ISSUE THREAD

**Issue by shgga2016** [giakki/uncss#291]
![image](https://cloud.githubusercontent.com/assets/19898146/23651055/3a387784-035f-11e7-9918-478a97b73f05.png)

**Comment by RyanZim** [comment]
@shgga2016 Please copy the complete error, including the stack trace, and post it here.

**Comment by shgga2016** [comment]
![2017-03-08 16 33 35](https://cloud.githubusercontent.com/assets/19898146/23696422/83748dd8-041e-11e7-845a-d73a0745b304.png)

@RyanZim

**Comment by RyanZim** [comment]
Hmm... Post the relevant part of your gulpfile.

**Comment by shgga2016** [comment]
Its just the offical DEMO
![2017-03-08 16 43 43](https://cloud.githubusercontent.com/assets/19898146/23733562/a2a950f8-04b4-11e7-975b-1e6bc1bc44d4.png)
@RyanZim

**Comment by RyanZim** [comment]
I'm no expert on gulp; @ben-eb do you have any ideas here?

@shgga2016 It would be helpful if you could make a reduced test case repo that contains the minimal amount of code to reproduce the bug. You can then push the repo to GitHub, and post the link here. We can clone the repo and attempt to reproduce/debug locally. Thanks!

**Comment by ben-eb** [comment]
gulp usage is fine, I think this is coming from phantomjs. Try googling the error message "TypeError: Bad argument phantom" and you will see a few issues, top one:

https://github.com/clearhead/clearhead/issues/2#issuecomment-151115747

Linking relevant issue: https://github.com/ben-eb/gulp-uncss/issues/77

**Comment by RyanZim** [comment]
@ben-eb Yeah, I suspected PhantomJS myself. Can't wait for the switch to jsdom.

**Comment by shgga2016** [comment]
Thanks

**Comment by mikelambert** [comment]
Uncss 0.15.0 just published, which includes the switch to jsdom.

**Comment by RyanZim** [comment]
Going to assume this is fixed.

**Comment by shgga2016** [comment]
Thank you.
