### ISSUE TITLE
Can it parse JSP files?

### ISSUE THREAD

**Issue by joacim-boive** [giakki/uncss#292]
Can I specify a number of JSP files to be parsed for CSS?
I understand that it can't build the JSP with all it's dependencies, but in my case it would be enough if it could read the JSP as-is for any CSS styling.

**Comment by RyanZim** [comment]
@joacim-boive It can parse anything that is valid HTML. JSP isn't valid HTML, so it can't parse that.

However, uncss can load URLs as well as files, so if start your dev server on localhost, you can run `uncss http://localhost/ > index.css` to get the CSS for the homepage...you get the idea.

Please close this issue. Thanks!

**Comment by RyanZim** [comment]
@mikelambert Can you close?

**Comment by joacim-boive** [comment]
Sorry, sorry... Closing.
