### ISSUE TITLE
uncss in vue project

### ISSUE THREAD

**Issue by jackPanyj** [giakki/uncss#293]
when i use vue-cli generate a project, it's rawHtml is just a `div`  with a id of `app`,  so the uncss remove other css rules, can it be used in a vue project?

**Comment by RyanZim** [comment]
@jackPanyj For SPAs, you are probably better off using https://github.com/purifycss/purifycss. It doesn't remove quite all the unused selectors, but it does remove some.

Please close this issue. Thanks!
