### ISSUE TITLE
CSS in JS file

### ISSUE THREAD

**Issue by extensionsapp** [giakki/uncss#294]
Hello.

If click on button, addet new class `open`. But uncss remove this class in style file.

![](https://i.gyazo.com/590a5b8f3b39b668ca8ab9620e9f1503.gif)

<img width="582" alt="screenshot_5" src="https://cloud.githubusercontent.com/assets/8192379/23898251/156e034c-08b9-11e7-989e-3cbcc1c3d6a1.png">

Is there some way that this style is also in the final style file?

**Comment by RyanZim** [comment]
@extensionsapp You need to use the `ignore` option. Example config:

```js
{
  ignore: ['open']
}
```

Alternately, you can add a comment before specific selectors:
```css
/* uncss:ignore */
.open {
    /* this rule will be ignored */
}

.unused {
    /* this will NOT be ignored */
}
```

Please close this issue. Thanks!

**Comment by extensionsapp** [comment]
@RyanZim Thanks for the answer.

<img width="618" alt="screenshot_5" src="https://cloud.githubusercontent.com/assets/8192379/23906286/2ba680fe-08d6-11e7-8374-6407364a2e4e.png">

In style.css I have many `.open` classes. And if I use command:
```
uncss -i .open http://localhost:33333/en/ > style2.css
```

`.open` class not saved to style2.css

**Comment by RyanZim** [comment]
Try:

    uncss -i /\.open/ http://localhost:33333/en/ > style2.css

The string has to exactly match the entire selector. Passing a regex will allow it to match selectors that contain `.open`.

**Comment by extensionsapp** [comment]
Thank you so much, @RyanZim.

**Comment by extensionsapp** [comment]
@RyanZim, how to use multi classes.

Not work.
```
-i /\.open|\active/
-i /(\.open|\.active)/
-i "/\.open|\.active/"
-i /\.open/, /\.active/
```

**Comment by RyanZim** [comment]
Not sure. Try `-i /\.open/ /\.active/` or `-i /\.open/ -i /\.active/`. If that doesn't work, use an `uncssrc` file (see docs for usage).

**Comment by extensionsapp** [comment]
Ignore only `.open`
`-i /\.open/ /\.active/`
Ignore only `.active`
`-i /\.open/ -i /\.active/`

.uncssrc nice work.
```
{
  "ignore": [
    "/.open/",
    "/.active/"
  ]
}
```
