### ISSUE TITLE
How to know if css is used if content is dynamically added via javascript?

### ISSUE THREAD

**Issue by inspiraller** [giakki/uncss#295]
Example:

**css**
```
.myblock ul{}
.myblock li{}
```

**html:**
```html
<div class="myblock">
</div>
<script src="myblock.js"></script>
```

**myblock.js**
```
$(function(){
$('.myblock').html(`
<ul>
 <li>hi</li>
</ul>
`)
})
```

**Comment by RyanZim** [comment]
@inspiraller If classes/elements are added with JS, you need to specify the relevant CSS selectors in the `ignore` option.

Please close this issue. Thanks!

**Comment by inspiraller** [comment]
That's not what I mean. The css will look like its unused if the html is not in the page yet. How does your plugin detect that?

**Comment by RyanZim** [comment]
> The css will look like its unused if the html is not in the page yet. How does your plugin detect that?

@inspiraller That's what I'm saying; uncss can't detect that, so you would need to manually ignore those selectors.

**Comment by mikelambert** [comment]
@RyanZim you're not reading his question correctly, you're expecting to read a different question :)

@inspiraller , it's because uncss loads the page in a headless browser, and lets it finish loading before checking for which html/css classes are used. Since your JS runs at startup (and not in response to user action), it works and is detected.

**Comment by RyanZim** [comment]
Oh, now I understand the question. Sorry about that! :disappointed:

**Comment by inspiraller** [comment]
So if my javascript runs after user interaction, how can I then trigger uncss to run?

**Comment by RyanZim** [comment]
@inspiraller When elements are added after user interaction, you need to use an `ignore` list; uncss only detects elements added during page load.

**Comment by mikelambert** [comment]
Alternately, you should run uncss on a special set of HTML pages that runs
your interaction JavaScript at load time, which will ensure all your css
elements get used (and seen).
2017年3月22日(水) 21:43 Ryan Zimmerman <notifications@github.com>:

**Comment by RyanZim** [comment]
@inspiraller @mikelambert Can one of you please close this?
