### ISSUE TITLE
[Feature Request] Uncss Google Font Imports

### ISSUE THREAD

**Issue by oleersoy** [giakki/uncss#296]
I'm making font utility library and was wondering if uncss supports, or would be interested in supporting, uncssing google font imports.  That way [superfly-css-utilities-fonts](https://github.com/superfly-css/superfly-css-utilities-fonts/blob/master/src/main/css/index.css) can import all google fonts during compile time / prototyping relying on uncss to remove once that will not be used.

This is a code snippet containing utility construction:
``` css
@import url('https://fonts.googleapis.com/css?family=Open+Sans:100,400,900');
...
.u-font-open-sans {
  font-family: "Open Sans", var(--font-family-helvetica-neue) !important;
}
```

**Comment by RyanZim** [comment]
@oleersoy This has been somewhat covered in https://github.com/giakki/uncss/issues/258. 

The conclusion was that uncss shouldn't mess with `font-face` declarations. Even if there are no CSS rules that use the font, the font is still usable, because it can be referenced from a style property directly. https://github.com/giakki/uncss/issues/258#issuecomment-250952792

For your use-case, you could probably run uncss as a postcss plugin, using https://github.com/ben-eb/postcss-discard-unused later in the plugin chain.

Hope this explains things clearly for you.

**Comment by oleersoy** [comment]
Hi @RyanZim 

I created a separate [superfly-css-task-deploy](https://www.npmjs.com/package/superfly-css-task-deploy) that can be run once prototyping with [superfly-css-task-build](https://www.npmjs.com/package/superfly-css-task-build) is complete.  

Ideally developers would be able perform their work like this in the prototyping stage:

``` html
<div class="u-font-roboto-500i-condensed">Some condensed and italicized looking roboto text</
<div class="u-font-open-sans-100-expanded">Some expanded looking opens sans text</div>
<div class="u-font-open-sans">400 weighted normal opens sans text</div>
....
``` 
The above could be done without having to import fonts because the [superfly-css-utilities-fonts](https://www.npmjs.com/package/superfly-css-utilities-fonts) module takes care of all the compile time imports.

So within the scope of the the [superfly-css framework](https://github.com/superfly-css/superfly-css) being able to remove all unused @font-face declarations that are not tied to a corresponding utility declaration would be really helpful, because the designer should never apply an imported font without using a utility.

I can see how it might not be desirable in the generic case though.  If there's any way I can "plug into" uncss to get this working I would definitely appreciate a heads up.

**Comment by RyanZim** [comment]
Not sure what would be the best approach here.

One way would be to use uncss as a postcss plugin https://github.com/giakki/uncss#as-a-postcss-plugin and then write a custom postcss plugin to strip unneeded google font imports.

Another approach would be to consider using something like https://github.com/jonathantneal/postcss-font-magician. Just something to consider.

**Comment by oleersoy** [comment]
Hmmm thanks for pointing that out!  https://github.com/jonathantneal/postcss-font-magician might be the perfect thing.  If it works the way that it looks like it works I could create all the font utilities and just leave the importing to the magician.

All the task I've written (build, deploy) use postcss BTW.

Just curious about one aspect of https://github.com/giakki/uncss/issues/258.  It says that uncss should not remove @font-face rules because an author could still inline the style.  I imagine that would be done sort of like this (`import-css.css`):

``` css
@font-face {
    font-family: myFirstFont;
    src: url(sansation_light.woff);
}
```
`index.html`
``` html
<div style="font-family: myFirstFont"> My first font text </div>
```
But what if index.html or any other html or javascript file does not reference `myFirstFont`.  It seems like it would be safe for uncss to remove the corresponding `@font-face` rule in this case or am I missing something?

In any case https://github.com/jonathantneal/postcss-font-magician might actually make a lot more sense since it uses an on-demand approach rather than a push one.  I'll have a more detailed look.  Thanks again.

**Comment by RyanZim** [comment]
> But what if index.html or any other html or javascript file does not reference myFirstFont. It seems like it would be safe for uncss to remove the corresponding @font-face rule in this case or am I missing something?

In that case, it would be safe for uncss to remove the `@font-face`. However, uncss doesn't check `style` attributes. Also, it can't check what elements (potentially containing `style` attributes) the JS adds due to user interaction. In short, it just requires too much overhead for uncss to try and process this in a safe way.

If this clears things up for you, please close this issue.

**Comment by oleersoy** [comment]
> uncss doesn't check style attributes.
Aha!  Gotcha.  I think I'm almost home free.

At compile and test time I'd like to make all the fonts available via utilities like these (The root variable is for baking in the font using the `@apply(--u-font-open-sans)` function):
``` css
:root {
  --u-font-open-sans {
    font-family: "Open Sans", var(--font-family-helvetica-neue) !important;
  }
}

.u-font-open-sans {
  font-family: "Open Sans", var(--font-family-helvetica-neue) !important;
}

.u-font-montserrat {
  font-family: Montserrat, var(--font-family-helvetica-neue) !important;
}
```
These would be imported at the top of the main stylesheet like this:
`import 'superfly-css-utilities-fonts';`

In this case every all the corresponding `@font-face` rules would be created by font-magician, which is hopefully not a big deal at design time.

I would then run the entire build again to produce the css to be deployed, but would run `uncss` before running `font-magician` and that would remove any of the unused `u-font...` utilities, and font-magician would then import only the ones that are used....Hopefully that does the trick!  Thanks again for all your input on this!

**Comment by mikelambert** [comment]
> Also, it can't check what elements (potentially containing style attributes) the JS adds due to user interaction.

Ryan, this argument is true, but I believe it a strawman.

Uncss can't also check what elements (potentially containing class elements) the JS adds due to user interaction. But that doesn't stop us from doing so, and making something useful called "uncss". :)

Uncss could be amended to check style attributes, and I would have no issues with that, as it's all very similar conceptually/procedurally to what is done with class attributes.

**Comment by RyanZim** [comment]
> Uncss could be amended to check style attributes, and I would have no issues with that, as it's all very similar conceptually/procedurally to what is done with class attributes.

Yeah, it could; but what's the point? In this user's case, they were actually asking about stripping Google font `@import` statements. To me, it seems like a lot of work for minimal benefit. If someone really needs `style` attributes checked, we can bikeshed that then IMHO.

**Comment by oleersoy** [comment]
I built this [superfly-css-task-deploy](https://github.com/superfly-css/superfly-css-task-deploy) task that does ended up  removing unused @font-face and @import statements.  It works like this.  
1) At design time everything is compiled from the `src` directory to the `target` directory.
2) At deploy time css is compiled from the target directory to the `deploy` directory but uncss strips everything that is not used in HTML (And soon javascript after I update the task).

Full demo here [superfly-css-component-button](https://github.com/superfly-css/superfly-css-component-button).

Run `npm run update` to install everything.  Run `npm run build` to build the test.  Finally run `gulp deploy:css` and `gulp deploy html` to deploy the minified and uncssed css and test html page correspondingly
