### ISSUE TITLE
Document how uncss works and common workarounds/integrations

### ISSUE THREAD

**Issue by mikelambert** [giakki/uncss#297]
Given the constant stream of uncss issues about a few major topics, it's probably worth a few bits of usage documentation in the README:
- uncss runs a web browser, parses the page, and inspects for used css classes
- uncss cannot be run on non-html pages. this includes templates and other such things. for that, you should probably generate example html pages from your templates, and run uncss on those generated files (or alternately, run a live local dev server, and point uncss at that)
- uncss does run javascript, but only whatever javascript is run on page load. it does (and cannot) not handle user interactions like button clicks or hovers. if you wish to protect that css, you must use css ignores, or generate a "special" version of your page that adds these selectors on page-load, specifically for detection (and preservation) by uncss

**Comment by RyanZim** [comment]
I've been thinking along similar lines, just never got time to open an issue/PR. I can try to do a PR for this, but don't know when I'll get time (some other pressing things ATM).
