### ISSUE TITLE
Regex in src urls

### ISSUE THREAD

**Issue by therayess** [giakki/uncss#301]
Trying to use url src as a file input, my url is a details page with parameters (id for example), my code is like this:

```js
files: [{
	    nonull: true,
	    src: ['http://sdfrontend.com/course/single'],
	    dest: 'frontend/web/css/single.css'
	}]
```

the actual page url is like this:
http://sdfrontend.com/course/single?id=61

Running uncss on that url won't match and won't work, i tried using regex in the src like so:

```js
src:['http:\/\/sdfrontend.com\/course\/single(\?|\&)([^=]+)\=([^&]+)']
```

didn't work, tried other regex's too but also didn't work.

How can i define the src to be a url with parameters ?

Thanks for your time

**Comment by therayess** [comment]
anyone? im simply trying to target pages with parameters, how can i do that? any feedback would be great, thanks

**Comment by mikelambert** [comment]
I believe you have to specify all the individual list of urls you want to
run uncss on, not a regex. With a regex, it is not able to enumerate and
know what urls to load and execute within the browser.

Mike
2017年5月7日(日) 21:27 Ammar Rayess <notifications@github.com>:

**Comment by therayess** [comment]
doesn't have to be regex, is there any way to target dynamic pages? or urls excluding query strings?

**Comment by mikelambert** [comment]
Actually....I have no idea what your example is from. `nonull`, `src`, and `dest` are not parameters described in the README at https://github.com/giakki/uncss. So it looks like this is not an uncss config...are you sure you're asking about the right project/config here? :)

But assuming you are actually using uncss, and just mistyped the example above....if you want to run uncss on dynamic pages, you just need to list the dynamic URL itself:
```
html: ['http://sdfrontend.com/course/single?id=61'],
```

**Comment by therayess** [comment]
Those options are coming from grunt-uncss actually, but the question is related to uncss config hence i'm asking here, so the problem is that the plugin is not usable in the case of dynamic pages, since you cannot specify ids for those pages, it could be id 61 or id=500, cannot list down the urls, would it be possible to include a functionality to target urls by regex or an option to set to have urls ignore query string (for future uses) ?

**Comment by mikelambert** [comment]
How would uncss know how to enumerate all the URLs on your site to check?

You have a bunch of IDs on your site. How is uncss supposed to find these URLs and HTML pages, to load them, check for used CSS, and clean up your CSS files? Is it supposed to just start guessing every possible ID on your website and loading them? Is it supposed to run a web crawler on your site to find every possible URL? Uncss just runs against a list of HTML pages that you provide.

You can use a bunch of file glogs on disk (*.html), or you can specify the pages/URLs directly (a.html). But it cannot automagically know what IDs are valid on your site and use them.

**Comment by mikelambert** [comment]
And to be clear, this has nothing to do with dynamic pages.

Even if you had a static list of pages (faq.html, help.html, contact.html, etc)....uncss would have no way to know how to "get all the html pages on your website".

It can get all the html pages in a directory on disk. But that's because the filesystem lets you "list" a directory. But there is no way to do that on a website at http://something-or-other...

**Comment by therayess** [comment]
Thats why i thought a regex check if doable would be a great addition, then i can specify something like:
http:\/\/sdfrontend.com\/course\/single(\?|\&)([^=]+)\=([^&]+)
and have uncss run on that base url ignoring the query string.

You clarified that a regex is not possible, so thanks for your response, i guess i'll have to find a way to make it work with a static list of urls as advised.

Thanks

**Comment by mikelambert** [comment]
Yes, you cannot use a regex. Unfortunately, your question about a regex makes it sound like you might not actually understand what uncss is doing or how it works, which is why I was trying to explain more...

Regardless, good luck getting it working with static url list! (It does not need to be exhaustive or complete. Just listing a few representative URLs should be sufficient.)
