### ISSUE TITLE
ReferenceError: Can't find variable: Set

### ISSUE THREAD

**Issue by lukasoppermann** [giakki/uncss#304]
Hey,

so I am getting the following error:

```
ReferenceError: Can't find variable: Set

  http://localhost:8080/js/webcomponents-lite.js:147
  http://localhost:8080/js/webcomponents-lite.js:192
```

The actual code is: `new Set("…`

Any idea why this shows up? Is it possible the phantomjs version does not support `Set`? Can I avoid this somehow?

Can I provide any more information that could help?

Thanks.

**Comment by RyanZim** [comment]
The latest version of PhantomJS does not support ES2015 `Set`.

You can try the experimental branch of uncss that uses jsdom instead of PhantomJS by installing `uncss-jsdom` instead. See https://github.com/giakki/uncss/pull/280

**Comment by lukasoppermann** [comment]
Thanks for the info, will try this.

**Comment by RyanZim** [comment]
@mikelambert can you close?
