### ISSUE TITLE
Unofficial server appears to be down

### ISSUE THREAD

**Issue by pricelessbrewing** [giakki/uncss#306]
Never used node before, and it seems excessive to learn for a one off usage, but the online server appears to not be working right now. Does anyone know if this is a temporary or permanent thing?

**Comment by mikelambert** [comment]
The online server is not officially supported, though we listed the server in the README for the convenience of folks like you. @simi , do you know the status of the server?

**Comment by simi** [comment]
Do you mean https://uncss-online.com/? That's up for me. Feel free to ping @pajasevi, he's author and maintainer of this project if you'll see any problems.

**Comment by pajasevi** [comment]
**Fixed!**

**Comment by pricelessbrewing** [comment]
Thanks!

**Comment by andreadd** [comment]
Dear @pajasevi https://uncss-online.com/ seems to be offline again. I was doing some tests to my pages with amazing results but I cannot reach the website. Thank you!

**Comment by RyanZim** [comment]
Up for me

**Comment by pajasevi** [comment]
It's already fixed, my VPS provider had some technical issues with the server.
