### ISSUE TITLE
 jquery,angular classes

### ISSUE THREAD

**Issue by itsmerahul** [giakki/uncss#309]
When a class is defined using jquery or angular, it is removed automatically. Is it a bug or am I doing something wrong?
For example, after including uncss-ed file,modals are not opening , the reason being that the class that is added through jquery on clicking a button, is removed by uncss. 
Is there any solution
and note that I am using grunt uncss

**Comment by itsmerahul** [comment]
and node that I am using grunt uncss

**Comment by RyanZim** [comment]
Use the `ignore` option:

> ignore (Array): provide a list of selectors that should not be removed by UnCSS. For example, styles added by user interaction with the page (hover, click), since those are not detectable by UnCSS yet. Both literal names and regex patterns are recognized.

**Comment by itsmerahul** [comment]
but there would be a lot of such classes. So it would not be a good solution as it would almost be similar to manual optimization

**Comment by mikelambert** [comment]
Yes, this is correct, sorry @itsmerahul .

We could possibly whitelist *all* jquery and angular classes, under the assumption that they *might* be used at runtime in ways we cannot detect. But then we'd be doing a lot less trimming, and the resulting CSS files might be nearly as large as before...and people would complain about how it's leaving in unused css classes. :)

Your options are:
- don't use Uncss :)
- manually list the "modal" CSS classes you wish to keep
- setup some extra html pages that load modals on-page-load, and pass those html pages to Uncss (which will then correctly detect that the modals are used)
- Make a "list of all jquery/angular dynamic CSS classes". I imagine that list might be beneficial to others as well, and perhaps we could make it as dropin config files that are included with this library, for those users who would rather have "too much CSS" than "too little CSS"

**Comment by RyanZim** [comment]
Closing for lack of action.
