### ISSUE TITLE
Ignore custom class name attribute

### ISSUE THREAD

**Issue by Pumych** [giakki/uncss#310]
Is there a possibility ignore custom named attributes in HTML? (Not to ignore specific selectors)
Let say I want to ignore all selectors in following "css-class" attribute:
`<div css-class="custom">Custom content</div>`

**Comment by mikelambert** [comment]
By "ignore", do you mean you want these kept in your css? Or that you want these removed from your css?

Uncss looks at pages the same as a web browser looks at them. If the web browser doesn't understand `css-class`, then no, uncss will not understand it either, and the attributes will be ignored. (Is this what you want?) As a result, it will see those classes as being not-in-use, and so will delete  `custom` from the resulting css.

If your web page is using clientside javascript to turn that `css-class` into a proper `class` attribute, then uncss should also process/run that clientside javascript, and create an HTML with those class elements in-use. And given that they would then be in-use, uncss would then not remove them from the generated trimmed css files, and you would see `custom` in the resulting css.

Those are basically your options, based on how Uncss works. Think of uncss like a web browser loading a webpage. And then walking the HTML tree to figure out what's in use. That's basically it.

**Comment by Pumych** [comment]
As you say, my web page is using clientside javascript to turn that css-class into a proper class attribute, so this a right answer. Thank you.
