### ISSUE TITLE
Replace jsdom with Chrome headless

### ISSUE THREAD

**Issue by gajus** [giakki/uncss#313]
There are a few simple abstractions, e.g. https://github.com/gwuhaolin/chrome-render

Related: https://github.com/pocketjoso/penthouse/issues/169

**Comment by RyanZim** [comment]
@gajus Why? What advantages does it have over jsdom?

**Comment by gajus** [comment]
It is a standards compliant browser engine.

**Comment by mikelambert** [comment]
`chromeRender` returns raw HTML, which is of no help to Uncss. We would need to call/manage `chrome-pool` directly if we were to do this.

Standards compliance is important, though as a headless engine trying to extract used CSS classes, we obviously don't care about rendering compliance as much as JS functionality compliance.

Do you know...does chrome-pool work on all platforms (including windows)?

Also, it seems to require that the user have chrome already-installed on their system, according to https://www.npmjs.com/package/chrome-pool . We do not want to have outside dependencies for Uncss that require more than just "npm install" to use.

**Comment by gajus** [comment]
> We do not want to have outside dependencies for Uncss that require more than just "npm install" to use.

Whats the argument for this?

Yes, it does require to have Chrome pre-installed.

You can use CDP directly (see https://github.com/pocketjoso/penthouse/issues/169#issuecomment-313778774); `chrome-pool` is unnecessary.

**Comment by mikelambert** [comment]
The argument for this is to make uncss as self contained and easy to install as possible.

If I install a project which depends on something that depends on uncss, I don't want every project having to add instructions saying "please remember to install chrome!"

Lijewise, CDP appears to avoid a chrome dependency by replacing it with a remote server dependency. Again, making it difficult to just install and use this project.

If this project had a ton of standards compliance issues, it might be worth considering. But I don't see many at all, so I'm not sure why it's worth making our users' lives more complicated, just to achieve standards compliance (which they don't seem to care about right now).

Hopefully that helps answer your question?

**Comment by gajus** [comment]
> If this project had a ton of standards compliance issues, it might be worth considering. But I don't see many at all, so I'm not sure why it's worth making our users' lives more complicated, just to achieve standards compliance (which they don't seem to care about right now).

Thus far I did not manage to make it work. Spent the last 50+ minutes plus patching step-by-step resources that JSDom is unable to load.

* `Storage` objects fails with an error.
* `//` URLs fail with an error.

And the extracted CSS is far from the CSS required to render page.

<img width="1920" alt="screen shot 2017-07-07 at 22 44 29" src="https://user-images.githubusercontent.com/973543/27978145-e1d7b41c-6365-11e7-8479-79bf5540b8f8.png">

Anyway, your project, do what you like.

**Comment by RyanZim** [comment]
`//` urls don't work because we're loading from `file://`. Chrome headless wouldn't fix this.

**Comment by gajus** [comment]
Solved by https://github.com/gajus/usus
