### ISSUE TITLE
v0.15 breaks with `csspath`

### ISSUE THREAD

**Issue by XhmikosR** [giakki/uncss#315]
Migrated from https://github.com/addyosmani/grunt-uncss/commit/bfde32feaec860b8d47ce40fdcc5be02e8b68e93

**Comment by mikelambert** [comment]
(Retagging the members from the original thread)

Looks like `fixtures/adjacent.css` (in the above test) is being searched against the root, instead of against the html file's directory that included it?

@RyanZim @vseventer any thoughts?

**Comment by XhmikosR** [comment]
This was caused by an issue in grunt-uncss's code and not an issue with uncss itself.
