### ISSUE TITLE
Replace grunt-mocha-cov

### ISSUE THREAD

**Issue by XhmikosR** [giakki/uncss#317]
This package is unmaintained so we should use something else.

**Comment by RyanZim** [comment]
I'd be willing to cut the grunt cruft and just roll a simple npm scripts solution. Thoughts?

**Comment by XhmikosR** [comment]
Agreed. The tasks here are so simple we are better off with plain npm
scripts.

**Comment by XhmikosR** [comment]
I started working on a branch. I'll push it to this repo and make a PR so that you guys can review and contribute too.
