### ISSUE TITLE
How to interact with React or vue?

### ISSUE THREAD

**Issue by SidKwok** [giakki/uncss#320]
Seems it is built for css and html, but How to use it in React or Vue?

**Comment by mikelambert** [comment]
It renders the page. So it executes the React at startup for an initial build.

If you have dynamic interactive elements beyond that, you are correct it will not work to catch those css classes. You can either whitelist them, avoid using Uncss, or use one of the bajillion React/Vue design patterns that let you avoid depending on stylesheet classes for React components.

**Comment by SidKwok** [comment]
Thanks for your reply.
