### ISSUE TITLE
Uncss with modernizr

### ISSUE THREAD

**Issue by mikemellor11** [giakki/uncss#327]
When using modernizr it would be useful to specify a list of checks so that uncss can slice that part of the style declaration before performing its check for existence. IE.

**Html**

`<html class="no-js no-csscalc" lang="en">`

or 

`<html class="no-js csscalc" lang="en">`

**Sass**

```
.no-csscalc .myClass{
    width: 100%;
}

.csscalc .myClass{
    width: calc(100% - 10px);
}
```

With the current implementation both of these would be removed as no-csscalc/csscalc isn't on the html tag on page load its added through js, even if it was i'd want both scenario's css keeping.

I know i could add myClass to the ignored list, but that quickly becomes tiresome and a manual process when you have lots of checks and lots of classes.

I could add no-csscalc and csscalc to the ignores but if i have 100 classes all surrounded in a modernizr class then there essentially no longer being processed they'll just all get bundled in even if they don't appear in the html.

A solution could be a new property

```
"modernizr": [
    "csscalc"
]
```

And in the uncss process you could strip the normal and no- version from css before performing the check.

So 

`.csscalc .myClass`

and 

`.no-csscalc .myClass`

would become 

`.myClass`

and that would be looked for inside the html?

Any thoughts?

**Comment by RyanZim** [comment]
This is an interesting idea/approach, however, it'd be fairly complex to implement.

I think it'd be better if we implemented https://github.com/giakki/uncss/issues/131 instead. That way, you could inject `document.html.classList.add('csscalc', 'no-csscalc');` into the page, resolving this issue by having both classes set before uncss runs.

**Comment by mikelambert** [comment]
Have you verified that uncss does not work properly here?

It should do a full page render and initialization, including executing all relevant JS at page render time.

So I would be curious why these css tags aren't working (whether specified in the html tag, or added at load time in JS).

Or is the JS that adds them not part of the page initialization? (In which case, what adds them?)

**Comment by RyanZim** [comment]
@mikelambert The issue here is that modernizer either adds `csscalc` or `no-csscalc` depending on whether browsers support CSS `calc()`. That way, you can write:

```css
.csscalc .foo {
  width: calc(50% - 2rem);
}
.no-csscalc .foo {
  width: 49%;
}
```
Uncss is going to strip some of those selectors since they are unused, however, @mikemellor11 wants to preserve both of those rules. For that reason, we should have a way to add them to `html` so they both are used when uncss runs.

**Comment by mikemellor11** [comment]
So the issue with adding the relevant classes to the html just before uncss runs is this.

Sass

```
.no-csscalc .myClass1{
    width: 100%;
}

.no-csscalc .myClass2{
    width: 50%;
}

.csscalc .myClass1{
    width: calc(100% - 10px);
}

.csscalc .myClass2{
    width: calc(50% - 10px);
}
```

Html (tags injected pre-uncss running)

```
<html class="no-js no-csscalc csscalc">
	<body>
		<div class="myClass1"></div>
	</body>
</html>
```

Then myClass2 will remain unstripped even though it doesn't appear in the html. Which is why im thinking we'll need to strip the modernizr specific classes explicitly before doing the check against the html essentially treating them as though they're not part of the selector.

**Comment by RyanZim** [comment]
> Then myClass2 will remain unstripped even though it doesn't appear in the html.

Incorrect. Here's the output from running that example:

```css
.no-csscalc .myClass1{
    width: 100%;
}

.csscalc .myClass1{
    width: calc(100% - 10px);
}
```

**Comment by mikemellor11** [comment]
You're 100% correct, i've just updated to the latest version of the package and the classes are indeed being stripped correctly. I guess #131  would be a valid solution but in the meantime i'll add all modernizr classes directly to the html and remove them just before modernizr kicks in.

**Comment by RyanZim** [comment]
Closing as https://github.com/giakki/uncss/issues/131 would be the best solution.
