### ISSUE TITLE
Line endings

### ISSUE THREAD

**Issue by RyanZim** [giakki/uncss#336]
We have a line ending problem. All of the code in this repo is LF AFAIK except `src/uncss.js`. That one file is mixed line endings, but is mostly CRLF. In my opinion, we should change that file to all LF, and add an `.editorconfig` file to keep it that way. Just wanted to get approval from the other maintainers before doing this.

**Comment by mikelambert** [comment]
Yup, consistency sounds great to me. And "oh well" to blame info, it's
still there if one is motivated.

**Comment by RyanZim** [comment]
Fixed in https://github.com/giakki/uncss/commit/4cb60b884b2693d0f9b222a0fbe772e4a8d5995e.
