### ISSUE TITLE
Getting error while parsing charset declaration in CSS

### ISSUE THREAD

**Issue by vivekaltruist** [giakki/uncss#357]
Hi,

I am getting the following error while parsing CSS file with **@charset "UTF-8";** declaration at the top

```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CssSyntaxError: uncss/node_modules/css: unable to parse App/Home/css/default-theme.css :
<css input>:2:1: Unknown word
	1:        /*** uncss> filename: App/Home/css/default-theme.css ***/
	2:     -> ﻿@charset "UTF-8";
```
I am running the following command line:
`uncss ./App/Home/index.html > stylesheet.css`

**Comment by RyanZim** [comment]
Unable to reproduce; please post a reduced test case repository.

**Comment by vivekaltruist** [comment]
[input.zip](https://github.com/giakki/uncss/files/1655147/input.zip)

**Comment by vivekaltruist** [comment]
This is only reproducible with a single css file. But when I do some edit on that file, it works fine.
