### ISSUE TITLE
uncss from the command line

### ISSUE THREAD

**Issue by a-le** [giakki/uncss#43]
It seems the doc contains errors, or it may be that my installation is not working properly.

this will produce near empty clean.css (it's as if file.html was seen as empty): 
`uncss -s style.css file.html > clean.css`

this works as expected : 
`cat file.html | uncss -s style.css > clean.css`

**Comment by RyanZim** [comment]
@brutalcrozt Please open a new issue if needed instead of commenting on old outdated threads.
