### ISSUE TITLE
Bootstrap dropdown error after uncss

### ISSUE THREAD

**Issue by guillaumevincent** [giakki/uncss#64]
Someone report a bug on grunt-uncss repository. 
https://github.com/addyosmani/grunt-uncss/issues/86

I've got the same issue on gulp-uncss. I think it's a uncss bug :

There is an issue when using uncss with bootstraps collapse element on the navigation.
I try to add the following ignore list without any success :

```
ignore: [
            // needed for Bootstrap's transitions
            ".fade",
            ".fade.in",
            ".collapse",
            ".collapse.in",
            ".collapsing",
            ".alert-danger"
        ],
```

does anyone has a fix to make my dropdown menu in my navbar working ?

here a jsbin with bootstrap uncss stylesheet: http://jsbin.com/bunoy/1/
http://jsbin.com/bunoy/1/edit/

**Comment by LoveAndHappiness** [comment]
Hi there, 

I still require assistance. I tried your implementation by inclucing the ignore list, now the uncss-task of my gulpfile looks like this:

```javascript
gulp.task('uncss', function() {
	return gulp.src('style.css')
		.pipe(uncss({
			html: ['uncss/uncss.html'],
			ignore: [
	            ".fade",
	            ".fade.in",
	            ".collapse",
	            ".collapse.in",
	            ".collapsing",
	            ".alert-danger",
	            ".open",
	            "/open+/"
 	       ]
		}))
		.pipe(gulp.dest(''));
});
```

But my Navbar still doesn't work. You can see it here:
1. http://metalotechnika.horyzon.de

And here is the working part, where I didn't use uncss:
2. http://metalotechnika.com

**Comment by ben-eb** [comment]
@LoveAndHappiness Are you sure that you recompiled the CSS and then ran UnCSS on it and that all went up to your web server? The `open` class is what Bootstrap uses for most of its 'toggleable' components, if you view source of your working example you'll see it mentioned about 50 times in the source code. I can't find any mention of it in your second example.

**Comment by LoveAndHappiness** [comment]
@ben-eb Yes, I see exactly what you mean. And yes I am 100% sure, that the css in the non-working version is my recompiled CSS and then ran UnCSS, since I am working with scss and have to always recompile it.

I see tat the <code>open</code> class wents missing, although I added ".open" to the ignore file, therefore I conclude the "ignore" part in my gulpfile must be the problem.

As I said, the reason those .open classes are not mentioned in my non-working example, is because uncss makes them disappear, though I have used this:

```javascript
       .pipe(uncss({
            html: ['uncss/uncss.html'],
            ignore: [
                ".fade",
                ".fade.in",
                ".collapse",
                ".collapse.in",
                ".collapsing",
                ".alert-danger",
                ".open",
                "/open+/"
           ]
        }))
```

**Comment by LoveAndHappiness** [comment]
@ben-eb additional information:
I talked to @guillaumevincent and he also said, that he currently doesn't use uncss, because it doesn't seem to work with bootstraps navbar anymore. :) 

Appreciate your help

**Comment by guillaumevincent** [comment]
I confirm, I doesn't use uncss anymore because my navbar is broken.
@esteinborn solution doesn't work on firefox : http://jsbin.com/suyihoto/2/edit

**Comment by guillaumevincent** [comment]
maybe this is related : https://github.com/giakki/uncss/issues/70

`[ ".fade", ".fade.in", ".collapse", ".collapse.in", ".collapsing", ".alert-danger", ".open", "/open+/" ]`

ignore option is transformed in a stange array mixing RegExp and String : "https://github.com/giakki/uncss/blob/master/bin/uncss"
`[ ".fade", ".fade.in", ".collapse", ".collapse.in", ".collapsing", ".alert-danger", ".open", /open+/ ]`

**Comment by ben-eb** [comment]
You shouldn't delimit RegExps with quotes. If you pass:

```js
{
            html: ['uncss/uncss.html'],
            ignore: [
                ".fade",
                ".fade.in",
                ".collapse",
                ".collapse.in",
                ".collapsing",
                ".alert-danger",
                /\.open/
           ]
}
```

That will match the `.open` class, and any selector that happens to use it.

**Comment by LoveAndHappiness** [comment]
Splendid. Thank you ben-eb, seems to work perfectly now.

**Comment by ben-eb** [comment]
Awesome. :+1:

**Comment by guillaumevincent** [comment]
thank you @ben-eb

**Comment by nicolascine** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by 7wonders** [comment]
:+1:  I also needed to add ".navbar-collapse.in" for scrolling in collapse mode to work properly.

**Comment by damienh** [comment]
having had this issue today I have found that this is the best mix: 

```
          ignore: [/\w\.in/,
                    ".fade",
                    ".collapse",
                    ".collapsing",
                    /(#|\.)navbar(\-[a-zA-Z]+)?/,
                    /(#|\.)dropdown(\-[a-zA-Z]+)?/,
                    /(#|\.)(open)/,
                    ".modal",
                    ".modal.fade.in",
                    ".modal-dialog",
                    ".modal-document",
                    ".modal-scrollbar-measure",
                    ".modal-backdrop.fade",
                    ".modal-backdrop.in",
                    ".modal.fade.modal-dialog",
                    ".modal.in.modal-dialog",
                    ".modal-open",
                    ".in",
                    ".modal-backdrop"]
```

**Comment by gregbriandavis** [comment]
Anyone have a list of the classes included in a bootstrap3 carousel?
