### ISSUE TITLE
UnCSS ignoring complex selectors

### ISSUE THREAD

**Issue by addyosmani** [giakki/uncss#74]
Hey @giakki :) 

Over in [Web Starter Kit](https://github.com/google/web-starter-kit) our basic layout uses a selector that looks like `.app-bar.open ~ main`. Unfortunately, this gets skipped by UnCSS, leaving us with a broken menu during our build, meaning we need to add an [ignore](https://github.com/google/web-starter-kit/blob/master/gulpfile.js#L100) in place to get this working.

Would it be possible to get some further testing done on why UnCSS is unable to handle such selectors correctly?

**Comment by letsila** [comment]
Hi !

Combining tow classes selectors like so `.first-class.second-class` is still skipped. I have tried to ignore them but still doesn't work. The selectors are vanished by uncss.
