### ISSUE TITLE
Markup in <script> tags not being parsed

### ISSUE THREAD

**Issue by mbritton** [giakki/uncss#81]
In my HTML, I'm using inline backbone templates in script tags. How can I get uncss to parse them? This is a single page application use case.

**Comment by ben-eb** [comment]
@XhmikosR Think this is referring to this pattern:

```twig
<script type="text/html" id="template-contact">
  <div class="contact">
    <strong><%= name %></strong>
    <span><%= email %></span>
  </div>
</script>
```

**Comment by JRigotti** [comment]
+1 
Angular's ngTemplate not working either
`<script type="text/ng-template" id="/tpl.html">`

**Comment by SyntaxRules** [comment]
+1

@JRigotti Another angular use case.

If I have packaged html files in a template cache (put there by [gulp-angular-templatecache](https://www.npmjs.com/package/gulp-angular-templatecache)) uncss can't read them. In the following example the css class `blue` would be uncss'ed away.

```js
angular.module("myApp").run(["$templateCache", function($templateCache) {$templateCache.put("aHtmlFile.html","<p class=\"blue\">This is my styled paragraph</p>");
```

**Comment by corysimmons** [comment]
+1

@giakki mentioned he'd put this in the new version of UnCSS. Any ETA on that?

**Comment by cklemming** [comment]
+1

**Comment by lt7** [comment]
+1

I think my scenario is similar, I have an inline jquery [script ](https://css-tricks.com/snippets/jquery/smooth-scrolling/) that contains a CSS value that I'm unable to ignore via regex. I've tried using /a|\[href|\*="#"|\]:not|\(|\[href="#quote-carousel"]/gmi, (and other variations) in the .ignore section but just get the following on execution - Error: Syntax error, unrecognized expression: a[href*="#"]:not([href="#quote-carousel"]

**Comment by RyanZim** [comment]
@lt7 Exactly what css selector(s) are you trying to match? If you are only trying to match one selector, you might be better off passing it as a string to `ignore`.

**Comment by RyanZim** [comment]
This is becoming pretty uncommon now that we have the `<template>` tag supported in everything except IE: http://caniuse.com/#feat=template

@mikelambert @XhmikosR Thoughts?

**Comment by RyanZim** [comment]
Going to close this as `wontfix`; if anyone disagrees strongly, feel free to reopen.
