### ISSUE TITLE
Absolute path in <script> tag, and template in js file

### ISSUE THREAD

**Issue by nicolasxu** [giakki/uncss#85]
This is all my html for a single page application. The majority of css selectors are in the app.js which is referenced relative to build root.  
Most of the styles are missing and I think is because of the two problems/question:
1) uncss cannot resolve the path of app.js. I need to start a httpster, mini http server in build folder, so that I can use 0.0.0.0:3333 in browser to view the app. Otherwise, the resource will not be loaded correctly due to the absolute path issue. 
2) html template is in app.js. Can uncss go through app.js file and index all selectors? 

question 2) is dependent on 1). 

Anyway, there is a real need for uncss. I am sure it will get better. Thank you!

````html
<!DOCTYPE html>
<html>
<head>
	<meta content charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Backbone Browserify</title>
	<link rel="stylesheet" type href="/css/app.css">
</head>
<body> 
	<div id="main"></div>
	<script type src="/js/app.js"></script>

</body>
</html>
````

**Comment by giakki** [comment]
Fixed, will be released with the new version of UnCSS!

**Comment by corysimmons** [comment]
Did this ever happen? Can UnCSS parse JS templates within `<script>` tags now?

**Comment by ben-eb** [comment]
@corysimmons Not yet. There is an open issue for markup within script tags here: https://github.com/giakki/uncss/issues/81

**Comment by corysimmons** [comment]
Thanks for the update Ben.
