### ISSUE TITLE
Getting "Error : Cannot find module 'uncss' "

### ISSUE THREAD

**Issue by ankitgoyal91** [giakki/uncss#89]
When i gave command in terminal :
node style.js

I got this error :
module.js:340
    throw err;
          ^
Error: Cannot find module 'uncss'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ankit/fkm/style.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

In style.js content is :
var uncss = require('uncss');

var files   = ['http://spokemachine.com'],
    options = {
        ignore       : ['#added_at_runtime', /test-[0-9]+/],
        media        : ['(min-width: 700px) handheld and (orientation: landscape)'],
        csspath      : '/home/ankit/',
        raw          : 'h1 { color: green }',
        //stylesheets  : ['lib/bootstrap/dist/css/bootstrap.css', 'src/public/css/main.css'],
        ignoreSheets : [/fonts.googleapis/],
        //urls         : ['http://localhost:3000/mypage', '...'], // Deprecated
        timeout      : 1000,
        //htmlroot     : 'public'
    };

uncss(files, options, function (error, output) {
    console.log(output);
});

/\* Look Ma, no options! */
uncss(files, function (error, output) {
    console.log(output);
});

/\* Specifying raw HTML */
var raw_html = '...';
uncss(raw_html, options, function (error, output) {
    console.log(output);
});

I have installed nodejs, npm and uncss successfully in Ubuntu 14.04 LTS.

Each answer is appreciated.

**Comment by umpirsky** [comment]
I can confirm last comment. [README](https://github.com/giakki/uncss#installation) should be updated.
