### ISSUE TITLE
Can't figure out --ignore syntax

### ISSUE THREAD

**Issue by Batmensch** [giakki/uncss#91]
Uncss seems to be, well, ignoring my ignore list.  For instance, I've got a webkit pseudo-class reference at the top of my .css file, but no matter what I use for ignore, these don't get passed through.  I'm using uncss from the command line:

uncss *.tpl -s ../docs/adm_style.css --ignore "::-webkit+"

(.tpl files are smarty templates)

How should this be written?

**Comment by mrzool** [comment]
@giakki Adding this syntax to the docs would be great, it took me a good while to dig it out.

**Comment by RyanZim** [comment]
@mrzool PR welcome IMO; FWIW, if you're ignoring more than a selector or two, you should probably use an uncssrc file.
